import { z } from 'zod';
import type { GeneratorOutput, QuestionGenerator, Rng } from './types';
import { fmtNumber, gcd, pick, uniqueDistractors, uniqueNumericDistractors } from './utils';

// Factors, multiples and primes: the prime factorisation of a composite, the full factor
// list, HCF and LCM (by prime factors and by product), the first multiple above a bound, the
// smallest prime factor of a number, and a perfect square root. The param table carries the
// composites and pairs, so every answer is computed from the printed numbers — no answer is
// estimated, and every factor list is generated by trial division rather than typed in.
//
// Distractors are the named errors: confusing HCF with LCM (the classic), using the product
// instead of the LCM, dropping one prime from a factorisation, and reading a square number's
// root as half the number.

const MODES = [
  'prime-factorisation',
  'factors-list',
  'hcf',
  'lcm',
  'first-multiple-above',
  'smallest-prime-factor',
  'sqrt',
] as const;

export const paramsSchema = z.object({
  modes: z.array(z.enum(MODES)).min(1).default([...MODES]),
  /** Composites to factorise, with small prime factors so the answer stays readable. */
  composites: z.array(z.number().int().min(4).max(400)).min(2),
  /** Pairs for the HCF/LCM modes. */
  pairs: z
    .array(z.tuple([z.number().int().min(2).max(200), z.number().int().min(2).max(200)]))
    .min(1),
  /** Multiples and the bound they must exceed. */
  multiples: z.array(z.number().int().min(2).max(20)).min(1),
  bounds: z.array(z.number().int().min(10).max(200)).min(1),
  /** Numbers whose smallest prime factor is asked for (1 is excluded: it has none). */
  numbers: z.array(z.number().int().min(2).max(200)).min(1),
  /** Perfect squares for the root mode. */
  squares: z.array(z.number().int().min(4).max(400)).min(1),
});
export type FactorsMultiplesParams = z.infer<typeof paramsSchema>;

type Mode = (typeof MODES)[number];

export interface FactorsValues {
  mode: Mode;
  n: number;
  a: number;
  b: number;
  multiple: number;
  bound: number;
  /** The computed answer (a count/root/value; 0 where the answer is a string). */
  answerValue: number;
  answer: string;
}

/** Prime factorisation as an exponent map, by trial division. */
export function primeFactors(n: number): Map<number, number> {
  const out = new Map<number, number>();
  let rest = n;
  for (let p = 2; p * p <= rest; p++) {
    while (rest % p === 0) {
      out.set(p, (out.get(p) ?? 0) + 1);
      rest /= p;
    }
  }
  if (rest > 1) out.set(rest, (out.get(rest) ?? 0) + 1);
  return out;
}

/** "2^4 × 3" in house LaTeX, with the exponent omitted when it is 1. */
export function factorisationString(n: number): string {
  const parts = [...primeFactors(n).entries()].map(([p, e]) => (e === 1 ? fmtNumber(p) : `${p}^{${e}}`));
  return `$${parts.join(' \\times ')}$`;
}

/** Every factor of n, ascending, by trial division to the square root. */
export function factorList(n: number): number[] {
  const out: number[] = [];
  for (let d = 1; d * d <= n; d++) {
    if (n % d === 0) {
      out.push(d);
      if (d !== n / d) out.push(n / d);
    }
  }
  return out.sort((x, y) => x - y);
}

export function isSquare(n: number): boolean {
  return Number.isInteger(Math.sqrt(n));
}

export function smallestPrimeFactor(n: number): number {
  for (let p = 2; p * p <= n; p++) if (n % p === 0) return p;
  return n;
}

const EMPTY: Omit<FactorsValues, 'mode' | 'answer' | 'answerValue'> = {
  n: 0,
  a: 0,
  b: 0,
  multiple: 0,
  bound: 0,
};

export function draw(params: FactorsMultiplesParams, rng: Rng): FactorsValues {
  const modes = params.modes ?? [...MODES];
  const composites = params.composites;
  const pairs = params.pairs;
  const multiples = params.multiples;
  const bounds = params.bounds;
  const numbers = params.numbers;
  const squares = params.squares;

  const numeric = (n: number): FactorsValues => ({
    ...EMPTY,
    mode: 'hcf',
    n: 0,
    answer: `$${fmtNumber(n)}$`,
    answerValue: n,
  });

  const feasible = modes.filter((mode) => {
    if (mode === 'prime-factorisation') return composites.some((n) => primeFactors(n).size > 1);
    if (mode === 'factors-list') return composites.length > 0;
    if (mode === 'hcf' || mode === 'lcm') return pairs.length > 0;
    if (mode === 'first-multiple-above') return multiples.length > 0 && bounds.length > 0;
    if (mode === 'smallest-prime-factor') return numbers.some((n) => n >= 2);
    return squares.some((s) => isSquare(s));
  });
  if (feasible.length === 0) {
    throw new Error('math-factors-multiples: no mode is feasible for this param table');
  }
  const mode = pick(feasible, rng);

  if (mode === 'prime-factorisation') {
    const n = pick(composites.filter((v) => primeFactors(v).size > 1), rng);
    return { ...numeric(0), mode, n, answer: factorisationString(n), answerValue: 0 };
  }

  if (mode === 'factors-list') {
    const n = pick(composites, rng);
    return { ...numeric(0), mode, n, answer: factorList(n).join(', '), answerValue: 0 };
  }

  if (mode === 'hcf') {
    const [a, b] = pick(pairs, rng);
    return { ...numeric(gcd(a, b)), mode, a, b };
  }

  if (mode === 'lcm') {
    const [a, b] = pick(pairs, rng);
    return { ...numeric((a * b) / gcd(a, b)), mode, a, b };
  }

  if (mode === 'first-multiple-above') {
    const multiple = pick(multiples, rng);
    const bound = pick(bounds, rng);
    const value = multiple * (Math.floor(bound / multiple) + 1);
    return { ...numeric(value), mode, multiple, bound };
  }

  if (mode === 'smallest-prime-factor') {
    const n = pick(numbers.filter((v) => v >= 2), rng);
    return { ...numeric(smallestPrimeFactor(n)), mode, n };
  }

  const square = pick(squares.filter((s) => isSquare(s)), rng);
  return { ...numeric(Math.sqrt(square)), mode, n: square };
}

export function build(values: FactorsValues, rng: Rng): GeneratorOutput {
  const { mode, n, a, b, multiple, bound, answer } = values;
  const numeric = (candidates: number[]): [string, string, string] =>
    uniqueNumericDistractors(values.answerValue, candidates, rng).map((v) => `$${fmtNumber(v)}$`) as [
      string,
      string,
      string,
    ];

  if (mode === 'prime-factorisation') {
    // Wrong-but-plausible factorisations: an exponent up or down, a prime dropped, and the
    // factorisation of a neighbouring composite.
    const primes = [...primeFactors(n).entries()];
    const [firstPrime, firstExponent] = primes[0];
    const variant = (fn: (map: Map<number, number>) => void): string => {
      const map = new Map(primes);
      fn(map);
      const parts = [...map.entries()]
        .filter(([, e]) => e > 0)
        .map(([p, e]) => (e === 1 ? fmtNumber(p) : `${p}^{${e}}`));
      return `$${parts.join(' \\times ')}$`;
    };
    const candidates = [
      variant((m) => m.set(firstPrime, firstExponent + 1)),
      variant((m) => m.set(firstPrime, firstExponent - 1)),
      variant((m) => m.delete(primes[primes.length - 1][0])),
      `$${fmtNumber(n)}$`,
    ];
    const pool = new Set<string>([factorisationString(n)]);
    for (let k = 2; k <= 12; k++) {
      const other = n + k;
      if (primeFactors(other).size > 1) pool.add(factorisationString(other));
    }
    return {
      stem: `What is the prime factorisation of $${fmtNumber(n)}$?`,
      correct: answer,
      distractors: uniqueDistractors(answer, candidates, [...pool], rng),
      explanation: `Divide by the smallest prime each time: $${fmtNumber(n)} = ${[...primeFactors(n).entries()]
        .map(([p, e]) => `${Array.from({ length: e }, () => fmtNumber(p)).join(' \\times ')}`)
        .join(' \\times ')} = ${answer.trim().replace(/^\$|\$$/g, '')}$. Every factor in the answer must be prime, and the product must return $${fmtNumber(n)}$.`,
    };
  }

  if (mode === 'factors-list') {
    const list = factorList(n);
    const drop = (index: number): string =>
      list.filter((_, i) => i !== index).join(', ');
    const mid = Math.floor(list.length / 2);
    const candidates = [
      drop(list.length - 2),
      drop(mid),
      [...list, n + 1].sort((x, y) => x - y).join(', '),
      [...list, 1].sort((x, y) => x - y).join(', '),
    ];
    const pool = new Set<string>();
    for (let k = 1; k <= 20; k++) if (k !== n) pool.add(factorList(k).join(', '));
    return {
      stem: `Which list shows all the factors of $${fmtNumber(n)}$?`,
      correct: answer,
      distractors: uniqueDistractors(answer, candidates, [...pool], rng),
      explanation: `The factors pair up: $1 \\times ${fmtNumber(n)}$, and so on, giving $${answer}$. $${fmtNumber(n + 1)}$ is not a factor because $${fmtNumber(n)} \\div ${fmtNumber(n + 1)}$ is not a whole number.`,
    };
  }

  if (mode === 'hcf') {
    const product = a * b;
    return {
      stem: `What is the HCF of $${fmtNumber(a)}$ and $${fmtNumber(b)}$?`,
      correct: answer,
      distractors: numeric([(a * b) / gcd(a, b), gcd(a, b) * 2, Math.min(a, b), gcd(a, b) ** 2]),
      explanation: `The highest common factor divides both numbers: ${answer} divides $${fmtNumber(a)}$ and $${fmtNumber(b)}$. $${fmtNumber((a * b) / gcd(a, b))}$ is the LCM — the smallest number both go into, not the largest factor they share.`,
    };
  }

  if (mode === 'lcm') {
    const hcf = gcd(a, b);
    return {
      stem: `What is the LCM of $${fmtNumber(a)}$ and $${fmtNumber(b)}$?`,
      correct: answer,
      distractors: numeric([hcf, a * b, (a * b) / hcf / 2, ((a * b) / hcf) * 2]),
      explanation: `The lowest common multiple is the first number both divide into: $${fmtNumber(a * b)} \\div \\text{HCF} = ${fmtNumber(a * b)} \\div ${fmtNumber(hcf)} = ${fmtNumber(values.answerValue)}$. $${fmtNumber(hcf)}$ is their HCF, and $${fmtNumber(a * b)}$ is only the LCM when they share no factor.`,
    };
  }

  if (mode === 'first-multiple-above') {
    const value = values.answerValue;
    return {
      stem: `What is the first multiple of $${fmtNumber(multiple)}$ that is greater than $${fmtNumber(bound)}$?`,
      correct: answer,
      distractors: numeric([value - multiple, value + multiple, multiple * Math.floor(bound / multiple), value + 1]),
      explanation: `$${fmtNumber(bound)} \\div ${fmtNumber(multiple)} = ${fmtNumber(
        Math.floor(bound / multiple)
      )}$ remainder ${fmtNumber(bound % multiple)}, so the last multiple at or below $${fmtNumber(bound)}$ is $${fmtNumber(
        multiple * Math.floor(bound / multiple)
      )}$ and the next one is $${fmtNumber(value)}$.`,
    };
  }

  if (mode === 'smallest-prime-factor') {
    const spf = values.answerValue;
    return {
      stem: `What is the smallest prime factor of $${fmtNumber(n)}$?`,
      correct: answer,
      distractors: numeric([n, Math.round(n / 2), spf === 2 ? 3 : 2, spf + 1]),
      explanation: `Test the primes in order. $${fmtNumber(spf)}$ divides $${fmtNumber(n)}$ exactly ($${fmtNumber(n)} \\div ${fmtNumber(
        spf
      )} = ${fmtNumber(n / spf)}$) and no smaller prime does, so $${fmtNumber(spf)}$ is the smallest prime factor.`,
    };
  }

  const root = values.answerValue;
  return {
    stem: `What is the value of $\\sqrt{${fmtNumber(n)}}$?`,
    correct: answer,
    distractors: numeric([root * 2, root + 1, root - 1, Math.round(n / 2)]),
    explanation: `$${fmtNumber(root)} \\times ${fmtNumber(root)} = ${fmtNumber(n)}$, so $\\sqrt{${fmtNumber(n)}} = ${fmtNumber(
      root
    )}$. Half of $${fmtNumber(n)}$ would be $${fmtNumber(n / 2)}$, which is not the square root.`,
  };
}

export const mathFactorsMultiples: QuestionGenerator<FactorsMultiplesParams> = {
  id: 'math-factors-multiples',
  difficulty: 'medium',
  paramsSchema,
  generate(params, rng) {
    return build(draw(params, rng), rng);
  },
};
