import { Topic } from './types';

const mathDPFunctions: Topic = {
  id: 'math-dp-functions',
  subjectId: 'math',
  title: 'Functions',
  description: 'Function notation, domain and range, composite and inverse functions, transformations, and odd/even functions.',
  ibLevel: 'DP',
  notes: [
    {
      id: 'fun-n1',
      heading: 'Function Notation, Domain, Range',
      body: 'A function is a rule that takes an input and produces exactly one output. Every IB question about functions starts with understanding these three ideas: notation, domain, and range.\n\n📌 Definition\nA function f maps each element of the domain to exactly one element of the range.\n\n    f: x → f(x)\n\n    x = input (independent variable)\n    f(x) = output (dependent variable)\n\n🔑 Domain and Range\n    Domain  = set of all valid inputs\n    Range   = set of all actual outputs\n\n    Example: f(x) = √(x − 2)\n        Domain:  x − 2 ≥ 0  →  x ≥ 2\n        Range:   √(x − 2) ≥ 0  →  f(x) ≥ 0\n\n💡 Worked Example 1 — Finding domain and range\nFind the domain and range of f(x) = 1/(x + 3).\n\n  Step 1: Identify restrictions on the domain\n    The denominator cannot be zero:\n    x + 3 ≠ 0  →  x ≠ −3\n\n  Step 2: State the domain\n    Domain: all real x, x ≠ −3\n\n  Step 3: Find the range\n    As x → −3, f(x) → ±∞. As x → ±∞, f(x) → 0.\n    f(x) can take any real value except 0.\n    Range: all real f(x), f(x) ≠ 0\n\n💡 Worked Example 2 — Using function notation\nFor f(x) = x³ + 1 with domain 2 ≤ x ≤ 10:\n\n  Step 1: Evaluate f(7)\n    f(7) = 7³ + 1 = 343 + 1 = 344\n\n  Step 2: Find the range\n    f(x) is increasing on [2, 10]\n    Minimum: f(2) = 2³ + 1 = 9\n    Maximum: f(10) = 10³ + 1 = 1001\n    Range: 9 ≤ f(x) ≤ 1001\n\n📎 Key Points to Remember\n• The domain must always be stated; if not stated, assume all real values that work\n• Use interval notation or inequalities to write domains and ranges\n• The vertical line test checks if a graph represents a function\n• ℝ means all real numbers; common subsets are ℤ (integers), ℚ (rationals), ℕ (natural numbers)\n\n⚠️ Common Mistake\nConfusing domain and range. The domain is about x-values (horizontal); the range is about y-values (vertical). When you see f(x) ≥ 0, that describes the range, not the domain.',
    },
    {
      id: 'fun-n2',
      heading: 'Composite and Inverse Functions',
      body: 'Composite functions chain two functions together. Inverse functions undo each other. Both are central to solving equations and modelling real-world problems.\n\n📌 Composite Function Definition\n    (f ∘ g)(x) = f(g(x))\n\n    Apply g first, then apply f to the result.\n    Order matters: (f ∘ g)(x) is usually NOT equal to (g ∘ f)(x).\n\n🔑 Domain of a Composite Function\n    Domain of f ∘ g = { x in domain of g  |  g(x) is in domain of f }\n\n📌 Inverse Function Definition\n    f⁻¹ reverses the mapping of f.\n\n    f(f⁻¹(x)) = x   and   f⁻¹(f(x)) = x\n\n    An inverse exists only if f is one-to-one (passes the horizontal line test).\n\n🔑 Finding the Inverse — Step by Step\n    Step 1: Write y = f(x)\n    Step 2: Swap x and y\n    Step 3: Solve for y\n    Step 4: Replace y with f⁻¹(x)\n\n💡 Worked Example 1 — Composite function\nGiven f(x) = √(x + 4) and g(x) = 3 + 2x, find (f ∘ g)(x).\n\n  Step 1: Write the composition\n    (f ∘ g)(x) = f(g(x)) = f(3 + 2x)\n\n  Step 2: Substitute into f\n    f(3 + 2x) = √((3 + 2x) + 4) = √(2x + 7)\n\n  Step 3: State the domain of the composite\n    Need 2x + 7 ≥ 0  →  x ≥ −7/2\n\n💡 Worked Example 2 — Finding an inverse\nFind the inverse of f(x) = 2x + 5.\n\n  Step 1: Let y = 2x + 5\n\n  Step 2: Swap x and y\n    x = 2y + 5\n\n  Step 3: Solve for y\n    x − 5 = 2y\n    y = (x − 5)/2\n\n  Step 4: Write the inverse\n    f⁻¹(x) = (x − 5)/2\n\n💡 Worked Example 3 — Restricted domain and inverse\nThe function f(x) = (x − 2)² + 5, x ≤ m has an inverse.\n\n  Step 1: Find the largest possible m\n    The parabola has vertex at (2, 5). To be one-to-one, restrict to one side of the vertex.\n    Largest m = 2 (so x ≤ 2)\n\n  Step 2: Find the inverse\n    y = (x − 2)² + 5\n    x = (y − 2)² + 5\n    (y − 2)² = x − 5\n    Since y ≤ 2 for the inverse, take the negative root:\n    y − 2 = −√(x − 5)\n    f⁻¹(x) = 2 − √(x − 5)\n\n  Step 3: Domain of f⁻¹\n    Range of f is f(x) ≥ 5, so domain of f⁻¹ is x ≥ 5\n\n📎 Key Points to Remember\n• The graph of f⁻¹ is the reflection of f in the line y = x\n• Domain of f becomes range of f⁻¹; range of f becomes domain of f⁻¹\n• Many-to-one functions can have inverses if the domain is restricted first\n• For quadratics, restrict at the vertex (x ≥ h or x ≤ h)\n• Self-inverse functions satisfy f = f⁻¹ (example: f(x) = 1/x)\n\n⚠️ Common Mistake\nGetting the order wrong in composite functions. (f ∘ g)(x) means g first, then f — the function closest to x is applied first. Also, forgetting to restrict the range when finding the inverse of a quadratic. If the original domain was x ≤ 2, the inverse must satisfy f⁻¹(x) ≤ 2, so you must choose the negative square root.',
    },
    {
      id: 'fun-n3',
      heading: 'Transformations',
      body: 'Transformations let you move, stretch, and flip graphs without redrawing from scratch. Knowing the rules saves time in exams and helps you sketch unfamiliar functions quickly.\n\n📌 Transformation Rules\nGiven y = f(x), each change below produces a specific geometric effect:\n\n    y = f(x) + a        vertical translation by a units (up if a > 0)\n    y = f(x − a)        horizontal translation by a units (right if a > 0)\n    y = a·f(x)          vertical stretch by factor a\n    y = f(ax)           horizontal stretch by factor 1/a\n    y = −f(x)           reflection in the x-axis\n    y = f(−x)           reflection in the y-axis\n\n🔑 Order Matters for Multiple Transformations\n    Horizontal transformations: apply in the REVERSE order of operations\n    Vertical transformations: apply in the NORMAL order of operations\n\n💡 Worked Example 1 — Identifying transformations\nDescribe the transformation that maps y = f(x) to y = 3f(x) − 2.\n\n  Step 1: Identify the vertical stretch\n    y = 3f(x) is a vertical stretch by factor 3\n\n  Step 2: Identify the vertical translation\n    y = 3f(x) − 2 is a translation down by 2 units\n\n  Step 3: State the order\n    Stretch first, then translate (normal order for vertical)\n\n💡 Worked Example 2 — Composite horizontal transformation\nDescribe the transformation that maps y = f(x) to y = f(2x − 1).\n\n  Step 1: Factor the argument\n    y = f(2x − 1) = f(2(x − 1/2))\n\n  Step 2: Identify the horizontal stretch\n    y = f(2x) is a horizontal stretch by factor 1/2\n\n  Step 3: Identify the horizontal translation\n    y = f(2(x − 1/2)) is a translation right by 1/2 unit\n\n  Step 4: State the order\n    Translate right by 1/2 first, then stretch horizontally by 1/2\n    (reverse order for horizontal transformations)\n\n📎 Key Points to Remember\n• Horizontal translations use (x − a) inside the function — counter-intuitive direction\n• Horizontal stretches use f(x/q) — stretch factor is q, not 1/q\n• Reflections are special cases of stretches with negative scale factors\n• Asymptotes move with translations but not with stretches in the perpendicular direction\n• For y = a·f(x) + b: stretch by a, then translate by b\n• For y = f(ax + b): translate by −b, then stretch by 1/a\n\n⚠️ Common Mistake\nThinking y = f(x + 3) shifts the graph right by 3. It shifts LEFT by 3. Remember: replace x with (x − a) for a right shift, so (x + 3) = (x − (−3)) means shift left 3 units. Another common error: confusing horizontal and vertical stretch factors — y = f(2x) compresses horizontally by 1/2, it does NOT stretch.',
    },
    {
      id: 'fun-n4',
      heading: 'Odd and Even Functions',
      body: 'Symmetry properties of functions simplify integration, graph sketching, and algebraic manipulation. Two important symmetry types are even and odd.\n\n📌 Definitions\n    Even function:  f(−x) = f(x)  for all x in the domain\n    Odd function:   f(−x) = −f(x)  for all x in the domain\n\n🔑 Geometric Meaning\n    Even → symmetric about the y-axis\n    Odd  → 180° rotational symmetry about the origin\n\n💡 Worked Example 1 — Testing for even\nShow that f(x) = x⁴ − 3x² is even.\n\n  Step 1: Find f(−x)\n    f(−x) = (−x)⁴ − 3(−x)²\n\n  Step 2: Simplify\n    f(−x) = x⁴ − 3x² = f(x)\n\n  Step 3: Conclude\n    Since f(−x) = f(x), the function is even.\n\n💡 Worked Example 2 — Testing for odd\nShow that f(x) = x³ − x is odd.\n\n  Step 1: Find f(−x)\n    f(−x) = (−x)³ − (−x) = −x³ + x\n\n  Step 2: Factor out −1\n    f(−x) = −(x³ − x) = −f(x)\n\n  Step 3: Conclude\n    Since f(−x) = −f(x), the function is odd.\n\n💡 Worked Example 3 — A function that is neither\nTest f(x) = x² + x for symmetry.\n\n  Step 1: Find f(−x)\n    f(−x) = (−x)² + (−x) = x² − x\n\n  Step 2: Compare with f(x) and −f(x)\n    f(−x) ≠ f(x)  (not even)\n    f(−x) ≠ −f(x) = −x² − x  (not odd)\n\n  Step 3: Conclude\n    The function is neither even nor odd.\n\n📎 Common Even and Odd Functions\n• Even: x², x⁴, cos x, |x|, constants\n• Odd: x, x³, sin x, tan x\n• Neither: most polynomials with both odd and even powers\n\n📎 Key Points to Remember\n• The sum of two even functions is even\n• The sum of two odd functions is odd\n• The product of two even functions is even\n• The product of two odd functions is even\n• The product of an even and an odd function is odd\n\n⚠️ Common Mistake\nAssuming all polynomial functions are either even or odd. Most functions are neither. Also, forgetting to test the ENTIRE function — you must substitute −x into every term, not just the ones that look convenient.',
    },
    {
      id: 'fun-n5',
      heading: 'Piecewise Functions',
      body: 'Piecewise functions use different formulas on different intervals. They model real-world situations where rules change at specific boundaries, like taxi fares or tax brackets.\n\n📌 Definition\nA piecewise function is defined by different expressions on different intervals.\n\n    f(x) = { g(x)   for x in interval A\n           { h(x)   for x in interval B\n\n    The intervals must not overlap.\n\n🔑 Evaluating a Piecewise Function\n    1. Identify which interval contains the input value\n    2. Use the corresponding formula\n    3. The domain is the union of all intervals\n\n💡 Worked Example 1 — Evaluating a piecewise function\nFor the piecewise function\n\n    f(x) = { 2x − 5   for −10 ≤ x ≤ 10\n           { 3x + 1   for x > 10\n\nFind f(0), f(10), and f(20).\n\n  Step 1: Evaluate f(0)\n    0 is in [−10, 10], so use f(x) = 2x − 5\n    f(0) = 2(0) − 5 = −5\n\n  Step 2: Evaluate f(10)\n    10 is in [−10, 10], so use f(x) = 2x − 5\n    f(10) = 2(10) − 5 = 15\n\n  Step 3: Evaluate f(20)\n    20 is in x > 10, so use f(x) = 3x + 1\n    f(20) = 3(20) + 1 = 61\n\n  Step 4: State the domain\n    Domain: x ≥ −10\n\n💡 Worked Example 2 — A real-world piecewise model\nA taxi charges $3 for the first 2 km and $2 per additional km. Write C(d) for distance d km.\n\n  Step 1: Define the intervals\n    First 2 km: flat rate\n    Beyond 2 km: additional charge\n\n  Step 2: Write the function\n    C(d) = { 3              for 0 < d ≤ 2\n           { 3 + 2(d − 2)   for d > 2\n\n  Step 3: Simplify the second piece\n    C(d) = 3 + 2d − 4 = 2d − 1  for d > 2\n\n  Step 4: Verify at the boundary\n    At d = 2: first piece gives 3\n    At d = 2: second piece gives 2(2) − 1 = 3  ✓\n\n📎 Key Points to Remember\n• Always check which interval the input belongs to before substituting\n• Graphs of piecewise functions may have jumps at boundary points\n• For continuous piecewise functions, the pieces must meet at the boundary\n• The domain is the union of all individual intervals\n• Piecewise models are common in economics (tax brackets), transport (fares), and physics (motion)\n\n⚠️ Common Mistake\nUsing the wrong formula at the boundary point. Always check whether the boundary value is included in the first interval (≤ or ≥) or the second interval (< or >). Also, when writing piecewise models from word problems, forgetting to subtract the initial amount from the variable — the charge for additional km is per km BEYOND the initial distance, not per total km.',
    },
  ],
  flashcards: [
    { id: 'fun-f1', term: 'Function definition', definition: 'Each input maps to exactly one output.', example: 'f(x)=x² is a function; x=y² is not.' },
    { id: 'fun-f2', term: 'Composite (f∘g)(x)', definition: 'Apply g first, then f: f(g(x)).', example: 'f(x)=x+1, g(x)=x² → (f∘g)(x)=x²+1' },
    { id: 'fun-f3', term: 'Inverse f⁻¹(x)', definition: 'Reverses f. Graph is reflection in y=x.', example: 'f(x)=2x+3 → f⁻¹(x)=(x−3)/2' },
    { id: 'fun-f4', term: 'Horizontal line test', definition: 'f has inverse iff every horizontal line meets graph at most once.', example: 'f(x)=x² fails; restrict to x≥0 → f⁻¹=√x' },
    { id: 'fun-f5', term: 'Even function', definition: 'f(−x)=f(x); symmetric about y-axis.', example: 'x⁴−3x²' },
    { id: 'fun-f6', term: 'Odd function', definition: 'f(−x)=−f(x); 180° symmetric about origin.', example: 'x³−x' },
    { id: 'fun-f7', term: 'Piecewise function', definition: 'A function defined by different expressions on different intervals.', example: 'f(x) = { 2x for x<1; x+1 for x≥1 }' },
    { id: 'fun-f8', term: 'Self-inverse function', definition: 'A function that is its own inverse: f(f(x)) = x.', example: 'f(x) = 1/x is self-inverse because f⁻¹(x) = 1/x.' },
    { id: 'fun-f9', term: 'Domain of a composite function', definition: 'The set of x in domain of g such that g(x) is in domain of f.', example: 'f(x)=√x, g(x)=x−3 → domain of f∘g is x≥3.' },
    { id: 'fun-f10', term: 'Identity property', definition: 'Applying a function and then its inverse returns the original input.', example: 'f⁻¹(f(x)) = x and f(f⁻¹(x)) = x (within respective domains).' },
  ],
  questions: [
    { id: 'fun-q1', stem: 'f(x)=3x−2, g(x)=x². (f∘g)(2)=?', choices: ['7', '25', '10', '13'], correctIndex: 2, explanation: 'f(g(2))=f(4)=10.' },
    { id: 'fun-q2', stem: 'Domain of f(x)=√(x−4):', choices: ['x>4', 'x≥4', 'x<4', 'all real x'], correctIndex: 1, explanation: 'x−4≥0 → x≥4.' },
    { id: 'fun-q3', stem: 'f(x)=2x+5. f⁻¹(x)=?', choices: ['(x+5)/2', '(x−5)/2', '2x−5', '(5−x)/2'], correctIndex: 1, explanation: 'y=2x+5, swap: x=2y+5→y=(x−5)/2.' },
    { id: 'fun-q4', stem: 'Which is even?', choices: ['x³', 'x²+1', 'x³+x', 'x²+x'], correctIndex: 1, explanation: 'f(−x)=x²+1=f(x).' },
    { id: 'fun-q5', stem: 'y=f(x) → 3 right, 2 down:', choices: ['f(x+3)+2', 'f(x−3)−2', 'f(x+3)−2', 'f(x−3)+2'], correctIndex: 1, explanation: 'Right: x→x−3; down: −2.' },
    { id: 'fun-q6', stem: 'Range of f(x)=x²−4:', choices: ['y≥−4', 'y>−4', 'y≤−4', 'all real y'], correctIndex: 0, explanation: 'x²≥0 → x²−4≥−4.' },
    { id: 'fun-q7', stem: 'f(x)=√x and g(x)=x−3. What is the domain of (f∘g)(x)?', choices: ['x≥0', 'x≥3', 'x≤3', 'all real x'], correctIndex: 1, explanation: '(f∘g)(x)=√(x−3). The output of g must lie in the domain of f, so x−3≥0 → x≥3.' },
    { id: 'fun-q8', stem: 'Which function is self-inverse (f = f⁻¹)?', choices: ['f(x)=2x', 'f(x)=x²', 'f(x)=1/x', 'f(x)=x+1'], correctIndex: 2, explanation: 'For f(x)=1/x, solving y=1/x gives x=1/y, so f⁻¹(x)=1/x=f(x). Its graph is also symmetric about y=x.' },
    { id: 'fun-q9', stem: 'A taxi charges $3 for the first 2 km and $2 per additional km. Which piecewise function gives the cost C(d) in dollars for distance d km?', choices: ['C(d)=3 for d≤2, C(d)=2d for d>2', 'C(d)=3 for d≤2, C(d)=3+2(d−2) for d>2', 'C(d)=3d for d≤2, C(d)=2d for d>2', 'C(d)=2 for d≤2, C(d)=3+2d for d>2'], correctIndex: 1, explanation: 'The first 2 km cost a flat $3. Beyond that, each extra kilometre adds $2, so the cost is 3+2(d−2).' },
    { id: 'fun-q10', stem: 'f(x)=1/(x+2) and g(x)=x−1. Find (g∘f)(x).', choices: ['1/(x+2)−1', 'x+1', '1/(x+1)', 'x−3'], correctIndex: 0, explanation: '(g∘f)(x)=g(f(x))=g(1/(x+2))=1/(x+2)−1=(1−x−2)/(x+2)=(−x−1)/(x+2).' },
    { id: 'fun-q11', stem: 'f(x)=x²−4x+5 is restricted to x≤2 so it has an inverse. What is f⁻¹(x)?', choices: ['2−√(x−1)', '2+√(x−1)', '2−√(x+1)', '√(x−1)−2'], correctIndex: 0, explanation: 'Complete the square: f(x)=(x−2)²+1. With x≤2, solving y=(x−2)²+1 gives x−2=−√(y−1), so x=2−√(y−1). Hence f⁻¹(x)=2−√(x−1).' },
    { id: 'fun-q12', stem: 'A cup of coffee cools from 90°C according to T(t)=70×0.9ᵗ+20, where t is minutes. What temperature does it approach long-term?', choices: ['76.7°C', '20°C', '90°C', '0°C'], correctIndex: 1, explanation: 'As t→∞, 0.9ᵗ→0, so T→20°C. This horizontal asymptote represents the room temperature the coffee approaches but never goes below.' },
  ],
};

export default mathDPFunctions;
