import { Topic } from './types';

const mathDPSequences: Topic = {
  id: 'math-dp-sequences',
  subjectId: 'math',
  title: 'Sequences & Series',
  description: 'Arithmetic and geometric sequences, series sums, sigma notation, and applications including compound interest.',
  ibLevel: 'DP',
  notes: [
    {
      id: 'seq-n1',
      heading: 'Arithmetic Sequences and Series',
      body: 'An arithmetic sequence is a list of numbers where each term changes by a fixed amount.\n\n📌 Definition\nA sequence is arithmetic if the difference between consecutive terms is constant:\n    d = uₙ₊₁ − uₙ\n\n🔑 Key Formulas\n    nth term:     uₙ = u₁ + (n − 1)d\n    Sum of n terms:\n        Sₙ = n/2 × [2u₁ + (n − 1)d]\n        or Sₙ = n/2 × (u₁ + uₙ)\n\n💡 Worked Example\nThe fourth term of an arithmetic sequence is 10 and the ninth term is 25. Find the first term and common difference.\n\n  Step 1: Set up two equations\n    u₄ = u₁ + 3d = 10\n    u₉ = u₁ + 8d = 25\n\n  Step 2: Subtract the first equation from the second\n    5d = 15\n    d = 3\n\n  Step 3: Substitute back to find u₁\n    u₁ + 3(3) = 10\n    u₁ = 1\n\n  Answer: u₁ = 1, d = 3\n\n💡 Worked Example\nFind the sum of the first 20 terms of the sequence 3, 7, 11, 15, ...\n\n  Step 1: Identify u₁ and d\n    u₁ = 3,  d = 7 − 3 = 4\n\n  Step 2: Use the sum formula\n    S₂₀ = 20/2 × [2(3) + (20 − 1)(4)]\n    S₂₀ = 10 × (6 + 76)\n    S₂₀ = 10 × 82\n    S₂₀ = 820\n\n📎 Key Points to Remember\n• Simple interest and straight-line depreciation both follow arithmetic patterns\n• The formula Sₙ = n/2 × (u₁ + uₙ) is fastest when you know the first and last terms\n• Use Sₙ = n/2 × [2u₁ + (n − 1)d] when you know the common difference instead\n\n⚠️ Common Mistake\nForgetting that the nth term formula uses (n − 1), not n. The first term already exists — you only add the common difference (n − 1) times.',
    },
    {
      id: 'seq-n2',
      heading: 'Geometric Sequences and Series',
      body: 'A geometric sequence is a list of numbers where each term is multiplied by a fixed amount to get the next.\n\n📌 Definition\nA sequence is geometric if the ratio between consecutive terms is constant:\n    r = uₙ₊₁ / uₙ\n\n🔑 Key Formulas\n    nth term:     uₙ = u₁ × r^(n − 1)\n    Sum of n terms (r ≠ 1):\n        Sₙ = u₁(r^n − 1) / (r − 1)\n        or Sₙ = u₁(1 − r^n) / (1 − r)\n\n💡 Worked Example\nThe sixth term of a geometric sequence is 486 and the seventh term is 1458. Find the common ratio and first term.\n\n  Step 1: Find the common ratio\n    r = u₇ / u₆ = 1458 / 486 = 3\n\n  Step 2: Use the nth term formula to find u₁\n    u₆ = u₁ × 3^5 = 486\n    u₁ × 243 = 486\n    u₁ = 2\n\n  Answer: r = 3, u₁ = 2\n\n💡 Worked Example\nA geometric sequence has u₁ = 25 and r = 0.8. Find u₅ and S₅.\n\n  Step 1: Find the fifth term\n    u₅ = 25 × (0.8)^4\n    u₅ = 25 × 0.4096\n    u₅ = 10.24\n\n  Step 2: Find the sum of five terms\n    S₅ = 25 × (1 − 0.8^5) / (1 − 0.8)\n    S₅ = 25 × (1 − 0.32768) / 0.2\n    S₅ = 25 × 3.3616\n    S₅ = 84.04\n\n📎 Real-World Applications\n• Compound interest: FV = PV × (1 + r)^n\n• Population growth and radioactive decay\n• Spread of bacteria and viruses\n\n⚠️ Common Mistake\nUsing the wrong sum formula. When r > 1, use Sₙ = u₁(r^n − 1)/(r − 1). When 0 < r < 1, use Sₙ = u₁(1 − r^n)/(1 − r) to avoid negative denominators.',
    },
    {
      id: 'seq-n3',
      heading: 'Sum to Infinity',
      body: 'Some geometric series keep adding up forever — yet they still settle on a single number.\n\n📌 Definition\nA geometric series converges when the terms get closer and closer to zero. This happens only when the common ratio is between −1 and 1.\n\n🔑 Formula\n    If |r| < 1:     S∞ = u₁ / (1 − r)\n    If |r| ≥ 1:     The series diverges (no finite sum)\n\n💡 Worked Example\nThe first three terms of a geometric sequence are 6, 2, and 2/3. Explain why the series converges and find the sum to infinity.\n\n  Step 1: Find the common ratio\n    r = 2 / 6 = 1/3\n\n  Step 2: Check convergence\n    |1/3| = 1/3 < 1\n    The series converges because |r| < 1.\n\n  Step 3: Calculate S∞\n    S∞ = 6 / (1 − 1/3)\n    S∞ = 6 / (2/3)\n    S∞ = 6 × 3/2\n    S∞ = 9\n\n💡 Worked Example\nDoes the series 1 + 1/2 + 1/4 + 1/8 + ... have a finite sum?\n\n  Step 1: Identify u₁ and r\n    u₁ = 1,  r = 1/2\n\n  Step 2: Check |r|\n    |1/2| < 1 → converges\n\n  Step 3: Calculate S∞\n    S∞ = 1 / (1 − 1/2) = 1 / (1/2) = 2\n\n📎 Key Points to Remember\n• Always verify |r| < 1 before applying the S∞ formula\n• The sum to infinity is a limit — the partial sums get closer and closer but never exceed it\n• Alternating sequences with negative r can still converge if |r| < 1\n\n⚠️ Common Mistake\nApplying S∞ = u₁/(1 − r) without checking |r| first. If r = 2, the formula gives a negative number, which is clearly wrong because the terms are all positive and growing.',
    },
    {
      id: 'seq-n4',
      heading: 'Sigma Notation',
      body: 'Sigma notation is a compact way to write the sum of many terms in a sequence.\n\n📌 Definition\nThe Greek letter Σ (sigma) means "sum." The expression to the right tells you what to add, and the limits above and below tell you where to start and stop.\n\n    Σ(k=m to n) uₖ = uₘ + uₘ₊₁ + ... + uₙ\n\n🔑 Key Properties\n    Σ(k=1 to n) [uₖ + vₖ] = Σ(k=1 to n) uₖ + Σ(k=1 to n) vₖ\n    Σ(k=1 to n) c·uₖ = c·Σ(k=1 to n) uₖ\n\n💡 Worked Example\nWrite u₁ + u₂ + u₃ + ... + u₆ in sigma notation, given uₙ = 2 × 3^(n−1).\n\n  Step 1: Identify the pattern\n    Each term has the form 2 × 3^(n−1)\n\n  Step 2: Write in sigma notation\n    Σ(n=1 to 6) 2 × 3^(n−1)\n\n💡 Worked Example\nEvaluate Σ(k=3 to 7) (2k + 1).\n\n  Step 1: Recognise the lower limit is not 1\n    Rewrite as Σ(k=1 to 7) (2k + 1) − Σ(k=1 to 2) (2k + 1)\n\n  Step 2: Evaluate each sum\n    Σ(k=1 to 7): 3 + 5 + 7 + 9 + 11 + 13 + 15 = 63\n    Σ(k=1 to 2): 3 + 5 = 8\n\n  Step 3: Subtract\n    63 − 8 = 55\n\n📎 Key Points to Remember\n• The variable below Σ is the index (commonly k, i, or n)\n• Always check whether the lower limit starts at 1 or another number\n• Identify whether the underlying sequence is arithmetic or geometric before applying a sum formula\n\n⚠️ Common Mistake\nChanging the limits incorrectly when rewriting a sigma expression. If you shift the index, you must adjust the limits AND the formula inside.',
    },
    {
      id: 'seq-n5',
      heading: 'Depreciation, Simple Interest & Compounding Periods',
      body: 'Financial mathematics uses sequences and series to model how money grows or shrinks over time.\n\n📌 Simple Interest\nInterest is paid only on the original principal. This creates an arithmetic sequence.\n\n    FV = PV × (1 + rt)\n\n    PV = present value (principal)\n    r = annual interest rate (as a decimal)\n    t = time in years\n\n📌 Compound Interest\nInterest is paid on the principal AND on previously earned interest. This creates a geometric sequence.\n\n    FV = PV × (1 + r/(100k))^(kn)\n\n    PV = present value\n    r = nominal annual interest rate (%)\n    k = compounding periods per year\n    n = number of years\n\n🔑 Common Values of k\n• Annually:      k = 1\n• Half-yearly:   k = 2\n• Quarterly:     k = 4\n• Monthly:       k = 12\n\n📌 Depreciation\nValue decreases by a fixed percentage each year. This is compound interest with subtraction.\n\n    FV = PV × (1 − r/100)^n\n\n💡 Worked Example\nKim invests MYR 2000 at a nominal annual rate of 2.5% compounded monthly. Find the value after 5 years.\n\n  Step 1: Identify the values\n    PV = 2000,  r = 2.5,  k = 12,  n = 5\n\n  Step 2: Substitute into the formula\n    FV = 2000 × (1 + 2.5/(100 × 12))^(12 × 5)\n    FV = 2000 × (1 + 0.002083...)^60\n    FV = 2000 × 1.133148...\n    FV ≈ 2266.30\n\n  Answer: MYR 2266.30\n\n💡 Worked Example\nA new laptop costs $1200 and depreciates by 20% each year. What is its value after 3 years?\n\n  Step 1: Use the depreciation formula\n    FV = 1200 × (1 − 20/100)^3\n    FV = 1200 × (0.8)^3\n    FV = 1200 × 0.512\n    FV = 614.40\n\n  Answer: $614.40\n\n📎 Key Points to Remember\n• Simple interest forms an arithmetic sequence (constant difference)\n• Compound interest and depreciation form geometric sequences (constant ratio)\n• More compounding periods per year means more interest earned\n\n⚠️ Common Mistake\nUsing r/k directly as a decimal without dividing by 100 first. The formula uses r as a percentage, so 5% becomes 5/(100k), not 5/k.',
    },
  ],
  flashcards: [
    { id: 'seq-f1', term: 'Arithmetic nth term', definition: 'uₙ = u₁ + (n−1)d', example: 'u₁=7, d=3 → u₁₀ = 7+27 = 34' },
    { id: 'seq-f2', term: 'Arithmetic series sum', definition: 'Sₙ = n/2·(2u₁ + (n−1)d)', example: '3+7+11+…20 terms: S₂₀=820' },
    { id: 'seq-f3', term: 'Geometric nth term', definition: 'uₙ = u₁·rⁿ⁻¹', example: 'u₁=4, r=1/2 → u₅ = 1/4' },
    { id: 'seq-f4', term: 'Geometric series sum', definition: 'Sₙ = u₁(rⁿ−1)/(r−1)', example: 'u₁=2, r=3, n=4: S₄=80' },
    { id: 'seq-f5', term: 'Sum to infinity', definition: 'S∞ = u₁/(1−r), |r|<1 only', example: 'u₁=6, r=1/3 → S∞=9' },
    { id: 'seq-f6', term: 'Compound interest', definition: 'FV = PV·(1+r)ⁿ', example: '$1000 at 5% 3yr ≈ $1157.63' },
    { id: 'seq-f7', term: 'Simple interest', definition: 'Interest paid only on the original principal; forms an arithmetic sequence.', example: '$1000 at 5% simple for 3yr → $1000 + $150 = $1150.' },
    { id: 'seq-f8', term: 'Depreciation', definition: 'Value decreases by a fixed percentage each year: FV = PV·(1−r/100)^n.', example: 'Car $20 000, 15%/yr: after 2yr = $14 450.' },
    { id: 'seq-f9', term: 'Alternating geometric sequence', definition: 'When r < 0, terms alternate positive and negative.', example: '3, −6, 12, −24, … has r = −2.' },
    { id: 'seq-f10', term: 'Compounding periods', definition: 'k = periods per year. FV = PV·(1+r/(100k))^(kn).', example: '6% compounded monthly: k=12, rate per month = 0.5%.' },
  ],
  questions: [
    { id: 'seq-q1', stem: 'Arithmetic: u₄=18, u₇=30. Common difference?', choices: ['3', '4', '5', '6'], correctIndex: 1, explanation: '3d = 30−18 = 12 → d = 4.' },
    { id: 'seq-q2', stem: 'Sum of first 20 terms of 3+7+11+…?', choices: ['780', '800', '820', '840'], correctIndex: 2, explanation: 'u₁=3, d=4. S₂₀=10·(6+76)=820.' },
    { id: 'seq-q3', stem: 'Geometric: u₁=3, r=2. u₈=?', choices: ['192', '256', '384', '512'], correctIndex: 2, explanation: '3·2⁷ = 3·128 = 384.' },
    { id: 'seq-q4', stem: 'Convergent: u₁=12, r=1/4. S∞?', choices: ['15', '16', '48', '14'], correctIndex: 1, explanation: '12/(1−1/4) = 12/(3/4) = 16.' },
    { id: 'seq-q5', stem: '$5000 at 4% compound interest for 3 years?', choices: ['$5600', '$5616', '$5624', '$5632'], correctIndex: 2, explanation: '5000×1.04³ ≈ 5624.' },
    { id: 'seq-q6', stem: 'A student invests £2000 at a nominal annual rate of 3.6% compounded monthly. What is the value after 5 years?', choices: ['£2360', '£2387', '£2394', '£2408'], correctIndex: 2, explanation: 'FV = 2000·(1+0.003)^60 ≈ 2000·1.197 = £2394. Monthly compounding beats annual (≈£2387) and simple interest (≈£2360).' },
    { id: 'seq-q7', stem: 'A new laptop costs $1200 and depreciates by 20% each year. What is its value after 3 years?', choices: ['$576', '$600', '$614', '$768'], correctIndex: 2, explanation: 'FV = 1200·(0.8)³ = 1200·0.512 = $614.40. $600 is linear depreciation (wrong model), $768 is after only 2 years.' },
    { id: 'seq-q8', stem: 'Which of the following geometric sequences does NOT have a finite sum to infinity?', choices: ['u₁=8, r=1/2', 'u₁=5, r=−0.3', 'u₁=10, r=0.99', 'u₁=3, r=−1.2'], correctIndex: 3, explanation: 'S∞ exists only when |r|<1. Here |−1.2|=1.2 ≥ 1, so the series diverges. The others all have |r|<1.' },
    { id: 'seq-q9', stem: 'A geometric sequence has u₁=2 and r=−3. What is u₆?', choices: ['−486', '486', '−162', '162'], correctIndex: 0, explanation: 'u₆ = 2·(−3)⁵ = 2·(−243) = −486. The negative ratio makes terms alternate; odd powers of r are negative.' },
    { id: 'seq-q10', stem: 'A geometric sequence has u₁=4 and r=1.5. Which term is the first to exceed 100?', choices: ['8th', '9th', '10th', '11th'], correctIndex: 1, explanation: 'Solve 4·1.5^(n−1) > 100. Taking logs: n−1 > ln25/ln1.5 ≈ 7.94, so n > 8.94. The 9th term (≈102.5) is first to exceed 100.' },
    { id: 'seq-q11', stem: 'Ali invests $2000 for 4 years at 5% per year. How much more would he earn with compound interest (compounded annually) than with simple interest?', choices: ['$20', '$31', '$40', '$50'], correctIndex: 1, explanation: 'Simple interest: 2000 + 4×100 = $2400. Compound: 2000×1.05⁴ ≈ $2431. The difference is about $31. Compound interest earns "interest on interest," so it outperforms simple interest over time.' },
  ],
};

export default mathDPSequences;
