import { Topic } from './types';

const mathDPBinomial: Topic = {
  id: 'math-dp-binomial',
  subjectId: 'math',
  title: 'The Binomial Theorem',
  description: "Pascal's triangle, binomial coefficients, expansion of (a+b)ⁿ, the general term, and finding specific terms.",
  ibLevel: 'DP',
  notes: [
    {
      id: 'bin-n1',
      heading: "Binomial Coefficients and Pascal's Triangle",
      body: "The binomial coefficient ⁿCᵣ tells us how many ways we can choose r objects from a set of n. It also appears as the coefficient of each term in a binomial expansion.\n\n📌 Definition\nThe binomial coefficient is defined as:\n    ⁿCᵣ = n! / (r!(n − r)!)\nwhere n! = n × (n − 1) × (n − 2) × ... × 2 × 1, and 0! = 1.\n\n▶️ Pascal's Triangle\nEach row n gives the coefficients for (a + b)ⁿ. To build the triangle:\n1. Start with 1 at the top\n2. Every row begins and ends with 1\n3. Each interior entry equals the sum of the two entries directly above it\n\n    Row 0:        1\n    Row 1:      1   1\n    Row 2:    1   2   1\n    Row 3:  1   3   3   1\n    Row 4: 1   4   6   4   1\n\n💡 Worked Example\nEvaluate ⁸C₃.\n\n  Step 1: Write the factorial formula\n    ⁸C₃ = 8! / (3! × 5!)\n\n  Step 2: Expand and cancel\n    ⁸C₃ = (8 × 7 × 6 × 5!) / (3! × 5!)\n    ⁸C₃ = (8 × 7 × 6) / (3 × 2 × 1)\n    ⁸C₃ = 336 / 6\n\n  Step 3: State the answer\n    ⁸C₃ = 56\n\n📎 Key Properties\n• Symmetry: ⁿCᵣ = ⁿCₙ₋ᵣ  (choosing r is the same as leaving out n − r)\n• ⁿC₀ = ⁿCₙ = 1\n• ⁿC₁ = ⁿCₙ₋₁ = n\n• The entries in row n of Pascal's triangle are ⁿC₀, ⁿC₁, ⁿC₂, ..., ⁿCₙ\n\n⚠️ Common Mistake\nForgetting that 0! = 1. When r = 0 or r = n, the formula still works because 0! = 1 by definition. Some students think 0! = 0, which breaks the calculation."
    },
    {
      id: 'bin-n2',
      heading: 'Binomial Expansion',
      body: "A binomial is an expression with two terms, like (a + b). Raising it to a power produces a binomial expansion with a predictable pattern.\n\n📌 The Binomial Theorem\nFor any positive integer n:\n    (a + b)ⁿ = ⁿC₀·aⁿ·b⁰ + ⁿC₁·aⁿ⁻¹·b¹ + ⁿC₂·aⁿ⁻²·b² + ... + ⁿCₙ·a⁰·bⁿ\n\nIn sigma notation:\n    (a + b)ⁿ = Σ(r=0 to n) ⁿCᵣ·aⁿ⁻ʳ·bʳ\n\n🔑 Key Observations\n• The expansion contains exactly n + 1 terms\n• Powers of a decrease from n down to 0\n• Powers of b increase from 0 up to n\n• The sum of powers in each term equals n\n\n💡 Worked Example 1\nExpand (x + 2)³.\n\n  Step 1: Identify row 3 of Pascal's triangle\n    Coefficients: 1, 3, 3, 1\n\n  Step 2: Apply the pattern\n    (x + 2)³ = 1·x³·2⁰ + 3·x²·2¹ + 3·x¹·2² + 1·x⁰·2³\n\n  Step 3: Simplify each term\n    (x + 2)³ = x³ + 3·x²·2 + 3·x·4 + 8\n    (x + 2)³ = x³ + 6x² + 12x + 8\n\n💡 Worked Example 2\nExpand (3 − x)⁴.\n\n  Step 1: Use coefficients from row 4\n    Coefficients: 1, 4, 6, 4, 1\n\n  Step 2: Substitute a = 3 and b = (−x)\n    (3 − x)⁴ = 1·3⁴ + 4·3³·(−x) + 6·3²·(−x)² + 4·3·(−x)³ + 1·(−x)⁴\n\n  Step 3: Simplify, watching signs\n    (3 − x)⁴ = 81 − 108x + 54x² − 12x³ + x⁴\n\n📎 Quick Reference: Common Expansions\n• (a + b)² = a² + 2ab + b²\n• (a + b)³ = a³ + 3a²b + 3ab² + b³\n• (a + b)⁴ = a⁴ + 4a³b + 6a²b² + 4ab³ + b⁴\n\n⚠️ Common Mistake\nForgetting brackets when substituting. If you expand (2x + 3)³, you must write (2x)³, not 2x³. The first gives 8x³; the second gives 2x³ — a big difference. Always wrap substituted expressions in brackets."
    },
    {
      id: 'bin-n3',
      heading: 'The General Term',
      body: "Instead of writing out the entire expansion, we can jump straight to any individual term using the general term formula. This is essential for finding specific coefficients or powers.\n\n📌 The General Term Formula\nThe (r + 1)th term in the expansion of (a + b)ⁿ is:\n    Tᵣ₊₁ = ⁿCᵣ·aⁿ⁻ʳ·bʳ\n\nRemember: r starts at 0, so the FIRST term is T₁ (when r = 0), not T₀.\n\n🔑 What Each Symbol Means\n• n = the power of the binomial\n• r = the term index minus 1 (0 for T₁, 1 for T₂, etc.)\n• a = the first term of the binomial\n• b = the second term of the binomial\n\n💡 Worked Example 1\nFind the 4th term of (2x + 3)⁵.\n\n  Step 1: Identify n, r, a, and b\n    n = 5,  r = 3 (because T₄ means r + 1 = 4)\n    a = 2x,  b = 3\n\n  Step 2: Substitute into the general term\n    T₄ = ⁵C₃·(2x)⁵⁻³·3³\n\n  Step 3: Evaluate\n    T₄ = 10·(2x)²·27\n    T₄ = 10·4x²·27\n    T₄ = 1080x²\n\n💡 Worked Example 2\nFind the coefficient of x³ in (1 + x)⁵.\n\n  Step 1: Set up the general term\n    Tᵣ₊₁ = ⁵Cᵣ·1⁵⁻ʳ·xʳ = ⁵Cᵣ·xʳ\n\n  Step 2: Match the power of x\n    We need x³, so r = 3\n\n  Step 3: Calculate the coefficient\n    Coefficient = ⁵C₃ = 10\n\n📎 Key Points\n• Tᵣ₊₁ always contains b raised to the power r\n• The power of a decreases by 1 for each subsequent term\n• If a or b contains x, simplify the powers carefully before extracting the coefficient\n\n⚠️ Common Mistake\nMixing up term number with r value. The 5th term uses r = 4, not r = 5. Since r starts at 0, subtract 1 from the term number to get r. Many exam errors come from using the wrong r."
    },
    {
      id: 'bin-n4',
      heading: 'Finding a Specific Term',
      body: "When a binomial contains variables with powers, finding a specific term — like the constant term or the x⁵ term — requires setting up an equation for the exponent.\n\n📌 The Strategy\n1. Write the general term: Tᵣ₊₁ = ⁿCᵣ·aⁿ⁻ʳ·bʳ\n2. Simplify the powers of x in this term\n3. Set the overall power of x equal to the target value\n4. Solve for r, then substitute back to find the term\n\n💡 Worked Example 1\nFind the constant term in the expansion of (x + 1/x)⁶.\n\n  Step 1: Write the general term\n    Tᵣ₊₁ = ⁶Cᵣ·x⁶⁻ʳ·(1/x)ʳ\n\n  Step 2: Combine powers of x\n    Tᵣ₊₁ = ⁶Cᵣ·x⁶⁻ʳ·x⁻ʳ\n    Tᵣ₊₁ = ⁶Cᵣ·x⁶⁻²ʳ\n\n  Step 3: Set power to zero for constant term\n    6 − 2r = 0\n    r = 3\n\n  Step 4: Find the term\n    T₄ = ⁶C₃·x⁰ = 20\n\n  The constant term is 20.\n\n💡 Worked Example 2\nFind the coefficient of x⁵ in (x² + 2/x)⁷.\n\n  Step 1: Write the general term\n    Tᵣ₊₁ = ⁷Cᵣ·(x²)⁷⁻ʳ·(2/x)ʳ\n\n  Step 2: Simplify powers of x\n    Tᵣ₊₁ = ⁷Cᵣ·x¹⁴⁻²ʳ·2ʳ·x⁻ʳ\n    Tᵣ₊₁ = ⁷Cᵣ·2ʳ·x¹⁴⁻³ʳ\n\n  Step 3: Match the required power\n    14 − 3r = 5\n    3r = 9\n    r = 3\n\n  Step 4: Calculate the coefficient\n    Coefficient = ⁷C₃·2³ = 35 × 8 = 280\n\n📎 When the Binomial Has a Product Factor\nIf the expression is (x + 3)(2x − 1)⁶, expand the binomial part first. Then multiply by (x + 3) and collect like terms. The x⁵ terms come from:\n• x × (the x⁴ term of the expansion)\n• 3 × (the x⁵ term of the expansion)\n\n⚠️ Common Mistake\nForgetting to include the numerical coefficient from the second term. In (x² + 2/x)⁷, the 2ʳ factor is easy to miss. Always carry the constant from b through the entire calculation."
    },
    {
      id: 'bin-n5',
      heading: 'Key Properties of Binomial Expansions',
      body: "Clever substitutions into (a + b)ⁿ reveal beautiful patterns in the binomial coefficients. These patterns are powerful tools for summing coefficients and checking your work.\n\n📌 Property 1: Sum of All Coefficients\nSetting a = 1 and b = 1 gives:\n    (1 + 1)ⁿ = ⁿC₀ + ⁿC₁ + ⁿC₂ + ... + ⁿCₙ\n    2ⁿ = ⁿC₀ + ⁿC₁ + ⁿC₂ + ... + ⁿCₙ\n\nThe sum of all binomial coefficients in row n equals 2ⁿ.\n\n💡 Worked Example\nWhat is the sum of all coefficients in (2x + 1)⁵?\n\n  Step 1: Substitute x = 1\n    Every term becomes its coefficient when x = 1\n\n  Step 2: Evaluate\n    (2·1 + 1)⁵ = 3⁵ = 243\n\n  The sum of all coefficients is 243.\n\n📌 Property 2: Alternating Sum of Coefficients\nSetting a = 1 and b = −1 gives:\n    (1 − 1)ⁿ = ⁿC₀ − ⁿC₁ + ⁿC₂ − ⁿC₃ + ... + (−1)ⁿ·ⁿCₙ\n    0 = ⁿC₀ − ⁿC₁ + ⁿC₂ − ⁿC₃ + ... + (−1)ⁿ·ⁿCₙ\n\nFor any n ≥ 1, the alternating sum of coefficients equals 0.\n\n💡 Worked Example\nVerify for n = 4:\n\n  Step 1: List the coefficients\n    Row 4: 1, 4, 6, 4, 1\n\n  Step 2: Apply alternating signs\n    1 − 4 + 6 − 4 + 1 = 0\n\n📌 Property 3: Power Pattern\nIn every term of (a + b)ⁿ:\n• The powers of a decrease by 1 from left to right\n• The powers of b increase by 1 from left to right\n• The sum of the powers in each term always equals n\n\n📎 Key Points to Remember\n• Substitute x = 1 to find the sum of coefficients in any polynomial\n• Substitute x = −1 to find the alternating sum of coefficients\n• The number of terms in (a + b)ⁿ is always n + 1\n• Symmetry: ⁿCᵣ = ⁿCₙ₋ᵣ means coefficients mirror around the centre\n\n⚠️ Common Mistake\nConfusing 'sum of coefficients' with 'sum of binomial coefficients'. The sum of binomial coefficients ⁿC₀ + ⁿC₁ + ... + ⁿCₙ is always 2ⁿ. But for (2x + 1)⁵, the coefficients are not just ⁵Cᵣ — they also include powers of 2. Use x = 1 to get the correct total directly."
    },
  ],
  flashcards: [
    { id: 'bin-f1', term: 'Binomial coefficient', definition: 'ⁿCᵣ = n!/(r!(n−r)!)', example: '⁸C₃ = 56' },
    { id: 'bin-f2', term: 'Binomial theorem', definition: '(a+b)ⁿ = Σ⁰ⁿ ⁿCᵣ·aⁿ⁻ʳ·bʳ', example: '(1+x)³ = 1+3x+3x²+x³' },
    { id: 'bin-f3', term: 'General term Tᵣ₊₁', definition: 'Tᵣ₊₁ = ⁿCᵣ·aⁿ⁻ʳ·bʳ', example: '(x+2)⁵: T₃=40x³' },
    { id: 'bin-f4', term: "Pascal's triangle", definition: 'Triangular array; row n = coefficients of (a+b)ⁿ', example: 'Row 4: 1,4,6,4,1' },
    { id: 'bin-f5', term: 'Sum of binomial coefficients', definition: 'The sum of all coefficients in row n equals 2ⁿ.', example: '⁴C₀+⁴C₁+⁴C₂+⁴C₃+⁴C₄ = 1+4+6+4+1 = 16 = 2⁴' },
    { id: 'bin-f6', term: 'Alternating sum of coefficients', definition: 'ⁿC₀ − ⁿC₁ + ⁿC₂ − ⁿC₃ + … + (−1)ⁿ·ⁿCₙ = 0', example: 'For n=4: 1 − 4 + 6 − 4 + 1 = 0' },
    { id: 'bin-f7', term: 'Number of terms', definition: 'The expansion of (a+b)ⁿ contains exactly n+1 terms.', example: '(a+b)⁵ has 6 terms, from r=0 to r=5.' },
    { id: 'bin-f8', term: 'Constant term', definition: 'The term independent of x — found by setting the overall power of x to zero.', example: 'In (x+1/x)⁶, the constant term is ⁶C₃ = 20.' },
  ],
  questions: [
    { id: 'bin-q1', stem: '⁷C₃ = ?', choices: ['21', '35', '42', '70'], correctIndex: 1, explanation: '7!/(3!4!) = 35.' },
    { id: 'bin-q2', stem: 'Coefficient of x³ in (1+x)⁵?', choices: ['5', '8', '10', '15'], correctIndex: 2, explanation: '⁵C₃ = 10.' },
    { id: 'bin-q3', stem: 'Coefficient of x² in (3−x)⁴:', choices: ['54', '36', '18', '9'], correctIndex: 0, explanation: '⁴C₂·3²·(−1)²=6·9·1=54.' },
    { id: 'bin-q4', stem: 'How many terms in (a+b)¹²?', choices: ['11', '12', '13', '24'], correctIndex: 2, explanation: 'n+1 = 13.' },
    { id: 'bin-q5', stem: '(1+0.02)⁶ ≈ ? (first 3 terms)', choices: ['1.12', '1.126', '1.13', '1.122'], correctIndex: 1, explanation: '1+6(0.02)+15(0.0004)=1.126.' },
    { id: 'bin-q6', stem: '(1+kx)⁴: coeff of x²=54. Find k.', choices: ['2', '3', '4', '5'], correctIndex: 1, explanation: '⁴C₂·k²=6k²=54→k=3.' },
    { id: 'bin-q7', stem: 'In the expansion of (a+b)ⁿ, which statement is always FALSE?', choices: ['The sum of coefficients is 2ⁿ', 'There are n+1 terms', 'The coefficient of aⁿb⁰ equals the coefficient of a⁰bⁿ', 'The expansion contains a term aⁿ⁺¹b⁻¹'], correctIndex: 3, explanation: 'Powers of a decrease from n to 0 and powers of b increase from 0 to n. No term can have a negative power or a power exceeding n.' },
    { id: 'bin-q8', stem: 'Find the coefficient of x⁵ in (x² + 2/x)⁷.', choices: ['280', '560', '140', '35'], correctIndex: 0, explanation: 'Tᵣ₊₁ = ⁷Cᵣ·(x²)⁷⁻ʳ·(2/x)ʳ = ⁷Cᵣ·2ʳ·x¹⁴⁻³ʳ. Set 14−3r=5 → r=3. Coefficient = ⁷C₃·2³ = 35×8 = 280.' },
    { id: 'bin-q9', stem: 'The probability of exactly r successes in 7 independent trials, each with success probability 0.3, is ⁷Cᵣ(0.3)ʳ(0.7)⁷⁻ʳ. What is the probability of exactly 2 successes?', choices: ['0.21', '0.25', '0.32', '0.44'], correctIndex: 2, explanation: '⁷C₂·(0.3)²·(0.7)⁵ = 21 × 0.09 × 0.16807 ≈ 0.3177 ≈ 0.32. This is a direct application of the binomial probability formula.' },
    { id: 'bin-q10', stem: 'What is the sum of all coefficients in the expansion of (2x + 1)⁵?', choices: ['32', '64', '243', '1024'], correctIndex: 2, explanation: 'Substitute x=1: (2·1+1)⁵ = 3⁵ = 243. When x=1, each term reduces to its coefficient, so the total equals the sum of all coefficients.' },
    { id: 'bin-q11', stem: 'Find the constant term in the expansion of (2x² + 1/x)⁶.', choices: ['15', '30', '60', '120'], correctIndex: 2, explanation: 'Tᵣ₊₁ = ⁶Cᵣ·(2x²)⁶⁻ʳ·(1/x)ʳ = ⁶Cᵣ·2⁶⁻ʳ·x¹²⁻³ʳ. For constant term: 12−3r=0 → r=4. T₅ = ⁶C₄·2² = 15×4 = 60.' },
    { id: 'bin-q12', stem: 'Find the coefficient of x³ in the expansion of (1 + x)⁴(1 − 2x).', choices: ['−8', '−4', '4', '8'], correctIndex: 0, explanation: 'Expand (1+x)⁴ = 1+4x+6x²+4x³+x⁴. Multiply by (1−2x): x³ terms come from 4x³·1 + 6x²·(−2x) = 4−12 = −8.' },
  ],
};

export default mathDPBinomial;
