import { Topic } from './types';

const mathDPSequences: Topic = {
  id: 'math-dp-sequences',
  subjectId: 'math',
  title: 'Sequences & Series',
  description: 'Arithmetic and geometric sequences, series sums, sigma notation, and applications including compound interest.',
  ibLevel: 'DP',
  notes: [
    {
      id: 'seq-n1',
      heading: 'Arithmetic Sequences and Series',
      body: 'An arithmetic sequence is a list of numbers where each term changes by a fixed amount.\n\n📌 Definition\nA sequence is arithmetic if the difference between consecutive terms is constant:\n    $$d = u_{n+1} - u_n$$\n\n🔑 Key Formulas\n    nth term:     $$u_n = u_1 + (n - 1)d$$\n    Sum of $n$ terms:\n        $$S_n = \\frac{n}{2} \\left[2u_1 + (n - 1)d\\right]$$\n        or $$S_n = \\frac{n}{2}(u_1 + u_n)$$\n\n💡 Worked Example\nThe fourth term of an arithmetic sequence is 10 and the ninth term is 25. Find the first term and common difference.\n\n  Step 1: Set up two equations\n    $$u_4 = u_1 + 3d = 10$$\n    $$u_9 = u_1 + 8d = 25$$\n\n  Step 2: Subtract the first equation from the second\n    $$5d = 15$$\n    $$d = 3$$\n\n  Step 3: Substitute back to find $u_1$\n    $$u_1 + 3(3) = 10$$\n    $$u_1 = 1$$\n\n  Answer: $u_1 = 1$, $d = 3$\n\n💡 Worked Example\nFind the sum of the first 20 terms of the sequence 3, 7, 11, 15, ...\n\n  Step 1: Identify $u_1$ and $d$\n    $$u_1 = 3, \\quad d = 7 - 3 = 4$$\n\n  Step 2: Use the sum formula\n    $$S_{20} = \\frac{20}{2} \\times \\left[2(3) + (20 - 1)(4)\\right]$$\n    $$S_{20} = 10 \\times (6 + 76)$$\n    $$S_{20} = 10 \\times 82$$\n    $$S_{20} = 820$$\n\n📎 Key Points to Remember\n• Simple interest and straight-line depreciation both follow arithmetic patterns\n• The formula $S_n = \\frac{n}{2}(u_1 + u_n)$ is fastest when you know the first and last terms\n• Use $S_n = \\frac{n}{2}\\left[2u_1 + (n - 1)d\\right]$ when you know the common difference instead\n\n⚠️ Common Mistake\nForgetting that the nth term formula uses $(n - 1)$, not $n$. The first term already exists — you only add the common difference $(n - 1)$ times.',
    },
    {
      id: 'seq-n2',
      heading: 'Geometric Sequences and Series',
      body: 'A geometric sequence is a list of numbers where each term is multiplied by a fixed amount to get the next.\n\n📌 Definition\nA sequence is geometric if the ratio between consecutive terms is constant:\n    $$r = \\frac{u_{n+1}}{u_n}$$\n\n🔑 Key Formulas\n    nth term:     $$u_n = u_1 \\times r^{n - 1}$$\n    Sum of $n$ terms ($r \\neq 1$):\n        $$S_n = \\frac{u_1(r^n - 1)}{r - 1}$$\n        or $$S_n = \\frac{u_1(1 - r^n)}{1 - r}$$\n\n💡 Worked Example\nThe sixth term of a geometric sequence is 486 and the seventh term is 1458. Find the common ratio and first term.\n\n  Step 1: Find the common ratio\n    $$r = \\frac{u_7}{u_6} = \\frac{1458}{486} = 3$$\n\n  Step 2: Use the nth term formula to find $u_1$\n    $$u_6 = u_1 \\times 3^5 = 486$$\n    $$u_1 \\times 243 = 486$$\n    $$u_1 = 2$$\n\n  Answer: $r = 3$, $u_1 = 2$\n\n💡 Worked Example\nA geometric sequence has $u_1 = 25$ and $r = 0.8$. Find $u_5$ and $S_5$.\n\n  Step 1: Find the fifth term\n    $$u_5 = 25 \\times (0.8)^4$$\n    $$u_5 = 25 \\times 0.4096$$\n    $$u_5 = 10.24$$\n\n  Step 2: Find the sum of five terms\n    $$S_5 = \\frac{25 \\times (1 - 0.8^5)}{1 - 0.8}$$\n    $$S_5 = \\frac{25 \\times (1 - 0.32768)}{0.2}$$\n    $$S_5 = 25 \\times 3.3616$$\n    $$S_5 = 84.04$$\n\n📎 Real-World Applications\n• Compound interest: $FV = PV \\times (1 + r)^n$\n• Population growth and radioactive decay\n• Spread of bacteria and viruses\n\n⚠️ Common Mistake\nUsing the wrong sum formula. When $r > 1$, use $S_n = \\frac{u_1(r^n - 1)}{r - 1}$. When $0 < r < 1$, use $S_n = \\frac{u_1(1 - r^n)}{1 - r}$ to avoid negative denominators.',
    },
    {
      id: 'seq-n3',
      heading: 'Sum to Infinity',
      body: 'Some geometric series keep adding up forever — yet they still settle on a single number.\n\n📌 Definition\nA geometric series converges when the terms get closer and closer to zero. This happens only when the common ratio is between $-1$ and $1$.\n\n🔑 Formula\n    If $|r| < 1$:     $$S_\\infty = \\frac{u_1}{1 - r}$$\n    If $|r| \\geq 1$:     The series diverges (no finite sum)\n\n💡 Worked Example\nThe first three terms of a geometric sequence are 6, 2, and $\\frac{2}{3}$. Explain why the series converges and find the sum to infinity.\n\n  Step 1: Find the common ratio\n    $$r = \\frac{2}{6} = \\frac{1}{3}$$\n\n  Step 2: Check convergence\n    $$\\left|\\frac{1}{3}\\right| = \\frac{1}{3} < 1$$\n    The series converges because $|r| < 1$.\n\n  Step 3: Calculate $S_\\infty$\n    $$S_\\infty = \\frac{6}{1 - \\frac{1}{3}}$$\n    $$S_\\infty = \\frac{6}{\\frac{2}{3}}$$\n    $$S_\\infty = 6 \\times \\frac{3}{2}$$\n    $$S_\\infty = 9$$\n\n💡 Worked Example\nDoes the series $1 + \\frac{1}{2} + \\frac{1}{4} + \\frac{1}{8} + \\ldots$ have a finite sum?\n\n  Step 1: Identify $u_1$ and $r$\n    $$u_1 = 1, \\quad r = \\frac{1}{2}$$\n\n  Step 2: Check $|r|$\n    $$\\left|\\frac{1}{2}\\right| < 1$$ → converges\n\n  Step 3: Calculate $S_\\infty$\n    $$S_\\infty = \\frac{1}{1 - \\frac{1}{2}} = \\frac{1}{\\frac{1}{2}} = 2$$\n\n📎 Key Points to Remember\n• Always verify $|r| < 1$ before applying the $S_\\infty$ formula\n• The sum to infinity is a limit — the partial sums get closer and closer but never exceed it\n• Alternating sequences with negative $r$ can still converge if $|r| < 1$\n\n⚠️ Common Mistake\nApplying $S_\\infty = \\frac{u_1}{1 - r}$ without checking $|r|$ first. If $r = 2$, the formula gives a negative number, which is clearly wrong because the terms are all positive and growing.',
    },
    {
      id: 'seq-n4',
      heading: 'Sigma Notation',
      body: 'Sigma notation is a compact way to write the sum of many terms in a sequence.\n\n📌 Definition\nThe Greek letter $\sum$ (sigma) means "sum." The expression to the right tells you what to add, and the limits above and below tell you where to start and stop.\n\n    $$\\sum_{k=m}^{n} u_k = u_m + u_{m+1} + \\ldots + u_n$$\n\n🔑 Key Properties\n    $$\\sum_{k=1}^{n} \\left[u_k + v_k\\right] = \\sum_{k=1}^{n} u_k + \\sum_{k=1}^{n} v_k$$\n    $$\\sum_{k=1}^{n} c \\cdot u_k = c \\cdot \\sum_{k=1}^{n} u_k$$\n\n💡 Worked Example\nWrite $u_1 + u_2 + u_3 + \\ldots + u_6$ in sigma notation, given $u_n = 2 \\times 3^{n-1}$.\n\n  Step 1: Identify the pattern\n    Each term has the form $2 \\times 3^{n-1}$\n\n  Step 2: Write in sigma notation\n    $$\\sum_{n=1}^{6} 2 \\times 3^{n-1}$$\n\n💡 Worked Example\nEvaluate $\\sum_{k=3}^{7} (2k + 1)$.\n\n  Step 1: Recognise the lower limit is not 1\n    Rewrite as $\\sum_{k=1}^{7} (2k + 1) - \\sum_{k=1}^{2} (2k + 1)$\n\n  Step 2: Evaluate each sum\n    $$\\sum_{k=1}^{7}: 3 + 5 + 7 + 9 + 11 + 13 + 15 = 63$$\n    $$\\sum_{k=1}^{2}: 3 + 5 = 8$$\n\n  Step 3: Subtract\n    $$63 - 8 = 55$$\n\n📎 Key Points to Remember\n• The variable below $\sum$ is the index (commonly $k$, $i$, or $n$)\n• Always check whether the lower limit starts at 1 or another number\n• Identify whether the underlying sequence is arithmetic or geometric before applying a sum formula\n\n⚠️ Common Mistake\nChanging the limits incorrectly when rewriting a sigma expression. If you shift the index, you must adjust the limits AND the formula inside.',
    },
    {
      id: 'seq-n5',
      heading: 'Depreciation, Simple Interest & Compounding Periods',
      body: 'Financial mathematics uses sequences and series to model how money grows or shrinks over time.\n\n📌 Simple Interest\nInterest is paid only on the original principal. This creates an arithmetic sequence.\n\n    $$FV = PV \\times (1 + rt)$$\n\n    $PV$ = present value (principal)\n    $r$ = annual interest rate (as a decimal)\n    $t$ = time in years\n\n📌 Compound Interest\nInterest is paid on the principal AND on previously earned interest. This creates a geometric sequence.\n\n    $$FV = PV \\times \\left(1 + \\frac{r}{100k}\\right)^{kn}$$\n\n    $PV$ = present value\n    $r$ = nominal annual interest rate ($\\%$)\n    $k$ = compounding periods per year\n    $n$ = number of years\n\n🔑 Common Values of $k$\n• Annually:      $k = 1$\n• Half-yearly:   $k = 2$\n• Quarterly:     $k = 4$\n• Monthly:       $k = 12$\n\n📌 Depreciation\nValue decreases by a fixed percentage each year. This is compound interest with subtraction.\n\n    $$FV = PV \\times \\left(1 - \\frac{r}{100}\\right)^n$$\n\n💡 Worked Example\nKim invests MYR 2000 at a nominal annual rate of $2.5\\%$ compounded monthly. Find the value after 5 years.\n\n  Step 1: Identify the values\n    $$PV = 2000, \\quad r = 2.5, \\quad k = 12, \\quad n = 5$$\n\n  Step 2: Substitute into the formula\n    $$FV = 2000 \\times \\left(1 + \\frac{2.5}{100 \\times 12}\\right)^{12 \\times 5}$$\n    $$FV = 2000 \\times (1 + 0.002083\\ldots)^{60}$$\n    $$FV = 2000 \\times 1.133148\\ldots$$\n    $$FV \\approx 2266.30$$\n\n  Answer: MYR 2266.30\n\n💡 Worked Example\nA new laptop costs \\$1200 and depreciates by $20\\%$ each year. What is its value after 3 years?\n\n  Step 1: Use the depreciation formula\n    $$FV = 1200 \\times \\left(1 - \\frac{20}{100}\\right)^3$$\n    $$FV = 1200 \\times (0.8)^3$$\n    $$FV = 1200 \\times 0.512$$\n    $$FV = 614.40$$\n\n  Answer: \\$614.40\n\n📎 Key Points to Remember\n• Simple interest forms an arithmetic sequence (constant difference)\n• Compound interest and depreciation form geometric sequences (constant ratio)\n• More compounding periods per year means more interest earned\n\n⚠️ Common Mistake\nUsing $r/k$ directly as a decimal without dividing by 100 first. The formula uses $r$ as a percentage, so $5\\%$ becomes $\\frac{5}{100k}$, not $\\frac{5}{k}$.',
    },
  ],
  flashcards: [
    { id: 'seq-f1', term: 'Arithmetic nth term', definition: '$u_n = u_1 + (n-1)d$', example: '$u_1=7$, $d=3$ \\rightarrow $u_{10} = 7+27 = 34$' },
    { id: 'seq-f2', term: 'Arithmetic series sum', definition: '$S_n = \\frac{n}{2}\\left[2u_1 + (n-1)d\\right]$', example: '$3+7+11+\\ldots$ 20 terms: $S_{20}=820$' },
    { id: 'seq-f3', term: 'Geometric nth term', definition: '$u_n = u_1 \\cdot r^{n-1}$', example: '$u_1=4$, $r=\\frac{1}{2}$ \\rightarrow $u_5 = \\frac{1}{4}$' },
    { id: 'seq-f4', term: 'Geometric series sum', definition: '$S_n = \\frac{u_1(r^n - 1)}{r - 1}$', example: '$u_1=2$, $r=3$, $n=4$: $S_4=80$' },
    { id: 'seq-f5', term: 'Sum to infinity', definition: '$S_\\infty = \\frac{u_1}{1-r}$, $|r|<1$ only', example: '$u_1=6$, $r=\\frac{1}{3}$ \\rightarrow $S_\\infty=9$' },
    { id: 'seq-f6', term: 'Compound interest', definition: '$FV = PV \\cdot (1+r)^n$', example: '\\$1000 at $5\\%$ 3yr $\\approx$ \\$1157.63' },
    { id: 'seq-f7', term: 'Simple interest', definition: 'Interest paid only on the original principal; forms an arithmetic sequence.', example: '\\$1000 at $5\\%$ simple for 3yr \\rightarrow \\$1000 + \\$150 = \\$1150.' },
    { id: 'seq-f8', term: 'Depreciation', definition: 'Value decreases by a fixed percentage each year: $FV = PV \\cdot \\left(1 - \\frac{r}{100}\\right)^n$.', example: 'Car \\$20 000, $15\\%$/yr: after 2yr = \\$14 450.' },
    { id: 'seq-f9', term: 'Alternating geometric sequence', definition: 'When $r < 0$, terms alternate positive and negative.', example: '$3, -6, 12, -24, \\ldots$ has $r = -2$.' },
    { id: 'seq-f10', term: 'Compounding periods', definition: '$k$ = periods per year. $FV = PV \\cdot \\left(1 + \\frac{r}{100k}\\right)^{kn}$.', example: '$6\\%$ compounded monthly: $k=12$, rate per month = $0.5\\%$.' },
  ],
  questions: [
    { id: 'seq-q1', stem: 'Arithmetic: $u_4=18$, $u_7=30$. Common difference?', choices: ['3', '4', '5', '6'], correctIndex: 1, explanation: '$3d = 30-18 = 12$ \\rightarrow $d = 4$.' },
    { id: 'seq-q2', stem: 'Sum of first 20 terms of $3+7+11+\\ldots$?', choices: ['780', '800', '820', '840'], correctIndex: 2, explanation: '$u_1=3$, $d=4$. $S_{20}=10\\cdot(6+76)=820$.' },
    { id: 'seq-q3', stem: 'Geometric: $u_1=3$, $r=2$. $u_8=?$', choices: ['192', '256', '384', '512'], correctIndex: 2, explanation: '$3\\cdot2^7 = 3\\cdot128 = 384$.' },
    { id: 'seq-q4', stem: 'Convergent: $u_1=12$, $r=\\frac{1}{4}$. $S_\\infty?$', choices: ['15', '16', '48', '14'], correctIndex: 1, explanation: '$\\frac{12}{1-\\frac{1}{4}} = \\frac{12}{\\frac{3}{4}} = 16$.' },
    { id: 'seq-q5', stem: '\\$5000 at $4\\%$ compound interest for 3 years?', choices: ['\\$5600', '\\$5616', '\\$5624', '\\$5632'], correctIndex: 2, explanation: '$5000\\times1.04^3 \\approx 5624$.' },
    { id: 'seq-q6', stem: 'A student invests £2000 at a nominal annual rate of $3.6\\%$ compounded monthly. What is the value after 5 years?', choices: ['£2360', '£2387', '£2394', '£2408'], correctIndex: 2, explanation: '$FV = 2000\\cdot(1+0.003)^{60} \\approx 2000\\cdot1.197$ £2394. Monthly compounding beats annual (£2387) and simple interest (£2360).' },
    { id: 'seq-q7', stem: 'A new laptop costs \\$1200 and depreciates by $20\\%$ each year. What is its value after 3 years?', choices: ['\\$576', '\\$600', '\\$614', '\\$768'], correctIndex: 2, explanation: '$FV = 1200\\cdot(0.8)^3 = 1200\\cdot0.512 = 614.40$ \\$614.40. \\$600 is linear depreciation (wrong model), \\$768 is after only 2 years.' },
    { id: 'seq-q8', stem: 'Which of the following geometric sequences does NOT have a finite sum to infinity?', choices: ['$u_1=8$, $r=\\frac{1}{2}$', '$u_1=5$, $r=-0.3$', '$u_1=10$, $r=0.99$', '$u_1=3$, $r=-1.2$'], correctIndex: 3, explanation: '$S_\\infty$ exists only when $|r|<1$. Here $|-1.2|=1.2 \\geq 1$, so the series diverges. The others all have $|r|<1$.' },
    { id: 'seq-q9', stem: 'A geometric sequence has $u_1=2$ and $r=-3$. What is $u_6?$', choices: ['-486', '486', '-162', '162'], correctIndex: 0, explanation: '$u_6 = 2\\cdot(-3)^5 = 2\\cdot(-243) = -486$. The negative ratio makes terms alternate; odd powers of $r$ are negative.' },
    { id: 'seq-q10', stem: 'A geometric sequence has $u_1=4$ and $r=1.5$. Which term is the first to exceed 100?', choices: ['8th', '9th', '10th', '11th'], correctIndex: 1, explanation: 'Solve $4\\cdot1.5^{n-1} > 100$. Taking logs: $n-1 > \\frac{\\ln 25}{\\ln 1.5} \\approx 7.94$, so $n > 8.94$. The 9th term ($\\approx 102.5$) is first to exceed 100.' },
    { id: 'seq-q11', stem: 'Ali invests \\$2000 for 4 years at $5\\%$ per year. How much more would he earn with compound interest (compounded annually) than with simple interest?', choices: ['\\$20', '\\$31', '\\$40', '\\$50'], correctIndex: 1, explanation: 'Simple interest: $2000 + 4\\times100 = 2400$ \\$2400. Compound: $2000\\times1.05^4 \\approx 2431$ \\$2431. The difference is about \\$31. Compound interest earns "interest on interest," so it outperforms simple interest over time.' },
  ],
};

export default mathDPSequences;
