import { Topic } from './types';

const mathDPTrig: Topic = {
  id: 'math-dp-trig',
  subjectId: 'math',
  title: 'Trigonometry',
  description: 'Radian measure, unit circle, exact values, Pythagorean identity, trig graphs and transformations, solving equations, sine rule, cosine rule, area of triangle, and double angle formulas.',
  ibLevel: 'DP',
  notes: [
    {
      id: 'dtr-n1',
      heading: 'Radian Measure and the Unit Circle',
      body: 'Radians give a natural way to measure angles by relating them directly to arc length. One full revolution is 360° or 2π radians.\n\n📌 Definition\nA radian is the angle subtended at the centre of a circle by an arc equal in length to the radius.\n    2π rad = 360°\n    π rad = 180°\n\n🔑 Converting Between Degrees and Radians\n    To radians:   multiply by π/180\n    To degrees:   multiply by 180/π\n\n💡 Worked Example — Converting Angles\nConvert 150° to radians and 5π/4 rad to degrees.\n\n  Step 1: Degrees to radians\n    150° × π/180 = 5π/6 rad\n\n  Step 2: Radians to degrees\n    5π/4 × 180/π = 225°\n\n📎 Common Exact Values\n• 30° = π/6\n• 45° = π/4\n• 60° = π/3\n• 90° = π/2\n• 180° = π\n• 270° = 3π/2\n\n🔑 Arc Length and Sector Area\nFor a circle of radius r and central angle θ (in radians):\n    Arc length:     l = rθ\n    Sector area:    A = ½ r²θ\n\n💡 Worked Example — Sector Calculations\nA sector has radius 6 cm and central angle π/3 rad. Find the arc length and sector area.\n\n  Step 1: Arc length\n    l = 6 × π/3 = 2π cm ≈ 6.28 cm\n\n  Step 2: Sector area\n    A = ½ × 6² × π/3 = ½ × 36 × π/3 = 6π cm² ≈ 18.85 cm²\n\n🔑 The Unit Circle\nOn a unit circle (radius = 1), any angle θ measured anticlockwise from the positive x-axis has terminal point:\n    (cos θ, sin θ)\n\nThis definition works for ALL angles, not just acute ones.\n\n📊 CAST Rule — Signs in Each Quadrant\n• Quadrant 1 (0° to 90°):   All positive\n• Quadrant 2 (90° to 180°):  Sine positive\n• Quadrant 3 (180° to 270°): Tangent positive\n• Quadrant 4 (270° to 360°): Cosine positive\n\nA helpful mnemonic: "All Students Take Calculus"\n\n⚠️ Common Mistake\nForgetting to check the quadrant when finding sin or cos from a known ratio. If sin θ = 1/2, θ could be 30° (Q1) OR 150° (Q2). Always draw a quick sketch.',
    },
    {
      id: 'dtr-n2',
      heading: 'Identities and Solving Equations',
      body: 'Trigonometric identities let you rewrite expressions and solve equations. The Pythagorean identity is the most important — it connects sine and cosine.\n\n📌 Definition\nAn identity is an equation that is true for ALL values of the variable (where both sides are defined).\n\n🔑 Pythagorean Identity\n    sin²θ + cos²θ = 1\n\nRearranged forms (useful for solving):\n    sin²θ = 1 − cos²θ\n    cos²θ = 1 − sin²θ\n\n💡 Worked Example — Using the Identity\nGiven cos θ = 3/5 and θ is in Q1, find sin θ.\n\n  Step 1: Substitute into the identity\n    sin²θ + (3/5)² = 1\n    sin²θ + 9/25 = 1\n\n  Step 2: Solve for sin²θ\n    sin²θ = 16/25\n\n  Step 3: Take the square root\n    sin θ = 4/5  (positive because θ is in Q1)\n\n🔑 Double Angle Formulas\n    sin 2θ = 2 sin θ cos θ\n    cos 2θ = cos²θ − sin²θ\n             = 2 cos²θ − 1\n             = 1 − 2 sin²θ\n    tan 2θ = 2 tan θ / (1 − tan²θ)\n\n💡 Worked Example — Double Angle\nIf sin θ = 1/√5 and cos θ = 2/√5, find cos 2θ.\n\n  Step 1: Choose the most convenient form\n    cos 2θ = cos²θ − sin²θ\n\n  Step 2: Substitute values\n    cos 2θ = (2/√5)² − (1/√5)²\n    cos 2θ = 4/5 − 1/5 = 3/5\n\n🔑 Solving Trigonometric Equations — Step-by-Step\n1. Isolate the trig ratio (sin, cos, or tan) if possible\n2. Find the principal value using inverse trig on your calculator\n3. Use symmetry and periodicity to find ALL solutions in the given interval\n4. For quadratics in sin or cos, substitute u = sin θ or u = cos θ, then factorise\n\n💡 Worked Example — Solving a Quadratic Trig Equation\nSolve 2 cos²θ − cos θ − 1 = 0 for 0° ≤ θ ≤ 360°.\n\n  Step 1: Substitute u = cos θ\n    2u² − u − 1 = 0\n\n  Step 2: Factorise\n    (2u + 1)(u − 1) = 0\n\n  Step 3: Solve for u\n    u = 1   or   u = −1/2\n    cos θ = 1   or   cos θ = −1/2\n\n  Step 4: Find all angles in [0°, 360°]\n    cos θ = 1 → θ = 0°\n    cos θ = −1/2 → θ = 120°, 240°\n\n  Answer: θ = 0°, 120°, 240°\n\n📎 Key Points to Remember\n• Always state the domain before solving\n• Sine and cosine repeat every 360° (or 2π rad)\n• Tangent repeats every 180° (or π rad)\n• Check your final answers by substituting back into the original equation\n\n⚠️ Common Mistake\nDividing both sides of an equation by sin θ or cos θ — this loses solutions where that term equals zero. Always factorise instead of dividing.',
    },
    {
      id: 'dtr-n3',
      heading: 'Graphs of Trigonometric Functions',
      body: 'Trigonometric functions are periodic — their graphs repeat forever. Understanding how the parameters transform the basic graphs is essential for modelling real-world cycles.\n\n📌 Definition\nA periodic function repeats its values at regular intervals. The shortest such interval is called the period.\n\n🔑 General Form of Sinusoidal Functions\n    y = a sin(b(x − c)) + d\n    y = a cos(b(x − c)) + d\n\nParameter meanings:\n• a = amplitude (vertical stretch; |a| is the height from midline to peak)\n• b = affects the period; period = 2π/|b| for sin/cos, or π/|b| for tan\n• c = phase shift (horizontal translation)\n• d = vertical shift (moves the principal axis up or down)\n\n💡 Worked Example — Finding Amplitude and Period\nFor y = 4 sin(3x) − 2, state the amplitude and period.\n\n  Step 1: Identify a and b\n    a = 4,  b = 3\n\n  Step 2: Calculate amplitude\n    Amplitude = |a| = 4\n\n  Step 3: Calculate period\n    Period = 2π/|b| = 2π/3\n\n  Step 4: Note the vertical shift\n    Principal axis is y = −2 (so the graph oscillates between y = 2 and y = −6)\n\n📊 Key Features of Basic Graphs\n\ny = sin x:\n• Passes through (0, 0)\n• Maximum at (π/2, 1)\n• Zero at (π, 0)\n• Minimum at (3π/2, −1)\n• Period: 2π\n\ny = cos x:\n• Starts at (0, 1)\n• Zero at (π/2, 0)\n• Minimum at (π, −1)\n• Period: 2π\n\ny = tan x:\n• Zero at (0, 0), (π, 0), etc.\n• Vertical asymptotes at x = π/2 + nπ\n• Period: π\n\n💡 Worked Example — Describing a Transformed Graph\nDescribe the transformation from y = cos x to y = −20 cos(3x).\n\n  Step 1: Amplitude\n    |−20| = 20. The amplitude is 20.\n\n  Step 2: Period\n    Period = 360°/3 = 120° (or 2π/3 rad)\n\n  Step 3: Reflection\n    The negative sign reflects the graph in the x-axis.\n\n📎 Key Points to Remember\n• Amplitude is always positive — take the absolute value of a\n• Phase shift is c units to the RIGHT (note the minus sign inside the bracket)\n• For tan graphs, there are no maxima or minima — the curve extends to ±∞\n\n⚠️ Common Mistake\nConfusing period with frequency. A larger value of b makes the graph MORE squashed horizontally (shorter period), not stretched. If b = 2, the period is halved.',
    },
    {
      id: 'dtr-n4',
      heading: 'Sine Rule, Cosine Rule, and Triangle Area',
      body: 'For non-right-angled triangles, we need three powerful tools: the sine rule, the cosine rule, and the area formula using sine. Each is suited to different given information.\n\n📌 Notation\nFor triangle ABC:\n• Side a is opposite angle A\n• Side b is opposite angle B\n• Side c is opposite angle C\n\n🔑 The Sine Rule\n    a/sin A = b/sin B = c/sin C\n\nOr equivalently:\n    sin A/a = sin B/b = sin C/c\n\nUse the sine rule when you know:\n• Two angles and one side (AAS or ASA)\n• Two sides and a non-included angle (SSA — but watch for the ambiguous case)\n\n💡 Worked Example — Sine Rule (AAS)\nIn triangle ABC, angle A = 40°, angle B = 70°, and side a = 8 cm. Find side b.\n\n  Step 1: Set up the sine rule\n    a/sin A = b/sin B\n\n  Step 2: Substitute known values\n    8/sin 40° = b/sin 70°\n\n  Step 3: Solve for b\n    b = 8 × sin 70° / sin 40°\n    b ≈ 11.7 cm (3 sf)\n\n🔑 The Cosine Rule\n    a² = b² + c² − 2bc cos A\n\nTo find an angle when all three sides are known:\n    cos A = (b² + c² − a²) / (2bc)\n\nUse the cosine rule when you know:\n• Two sides and the included angle (SAS)\n• All three sides (SSS)\n\n💡 Worked Example — Cosine Rule (SAS)\nFind side a when b = 5 cm, c = 7 cm, and angle A = 60°.\n\n  Step 1: Apply the cosine rule\n    a² = 5² + 7² − 2 × 5 × 7 × cos 60°\n\n  Step 2: Calculate\n    a² = 25 + 49 − 70 × 0.5\n    a² = 74 − 35 = 39\n\n  Step 3: Solve\n    a = √39 ≈ 6.24 cm (3 sf)\n\n🔑 Area of a Triangle\n    Area = ½ ab sin C\n\nUse this when you know two sides and the included angle.\n\n💡 Worked Example — Area Formula\nA triangle has sides 9 cm and 12 cm with an included angle of 45°. Find its area.\n\n  Step 1: Substitute into the formula\n    Area = ½ × 9 × 12 × sin 45°\n\n  Step 2: Evaluate\n    Area = 54 × (√2/2) = 27√2 cm² ≈ 38.2 cm²\n\n📎 When to Use Each Rule\n• Sine rule: AAS, ASA, SSA (with caution)\n• Cosine rule: SAS, SSS\n• Area formula: two sides and included angle\n\n⚠️ Common Mistake\nUsing the cosine rule with the wrong angle. The angle in cos A must be the included angle between sides b and c. If you are finding angle A, make sure side a is opposite it.',
    },
    {
      id: 'dtr-n5',
      heading: 'The Ambiguous Case of the Sine Rule',
      body: 'When you are given two sides and a non-included acute angle (SSA), the sine rule can sometimes produce TWO valid triangles. This is called the ambiguous case.\n\n📌 Definition\nThe ambiguous case occurs when using the sine rule with SSA data, specifically when the side opposite the given angle is SHORTER than the other known side but LONGER than the altitude from the other known side.\n\n🔑 The Three Possibilities\nGiven angle A (acute), side a (opposite A), and side b (adjacent to A):\n\n    Calculate the altitude:  h = b sin A\n\nThen compare a with h and b:\n\n1. If a < h → no triangle is possible\n2. If a = h → exactly one right-angled triangle\n3. If h < a < b → TWO triangles are possible\n4. If a ≥ b → exactly one triangle\n\n💡 Worked Example — The Ambiguous Case\nIn triangle ABC, a = 8, b = 12, and angle A = 35°. Determine how many triangles can be formed.\n\n  Step 1: Calculate the altitude\n    h = b sin A = 12 × sin 35° ≈ 6.88\n\n  Step 2: Compare a with h and b\n    h ≈ 6.88 < a = 8 < b = 12\n\n  Step 3: Conclusion\n    Since h < a < b, TWO triangles are possible.\n\n  Step 4: Find both solutions (optional working)\n    Using sin B = (b sin A)/a = (12 sin 35°)/8 ≈ 0.860\n\n    Solution 1: B ≈ 59.4° (acute)\n    Solution 2: B ≈ 180° − 59.4° = 120.6° (obtuse)\n\n    Both give valid triangles because A + B < 180° in each case.\n\n🔑 Why Two Solutions Exist\nThe sine function is positive in both Quadrant 1 and Quadrant 2. So if sin B = k (where 0 < k < 1), there are two possible angles:\n    B = sin⁻¹(k)     (acute)\n    B = 180° − sin⁻¹(k)   (obtuse)\n\nBoth may give valid triangles if the angle sum does not exceed 180°.\n\n📎 Key Points to Remember\n• The ambiguous case ONLY happens with SSA and an acute given angle\n• If the given angle is obtuse or right, there is at most one triangle\n• Always check whether A + B < 180° for each possible value of B\n\n⚠️ Common Mistake\nForgetting to check the second (obtuse) solution. When you use sin⁻¹ on your calculator, it always gives the acute angle. You must also consider 180° minus that value.',
    },
  ],
  flashcards: [
    { id: 'dtr-f1', term: 'Radian', definition: '1 rad = angle subtended by arc equal to radius. 2π rad = 360°.', example: '150° = 150×π/180 = 5π/6 rad.' },
    { id: 'dtr-f2', term: 'Pythagorean Identity', definition: 'sin²θ + cos²θ = 1', example: 'If cosθ=3/5, sinθ=±4/5.' },
    { id: 'dtr-f3', term: 'Sine Rule', definition: 'a/sinA = b/sinB = c/sinC', example: 'A=40°, B=70°, a=8 → b≈11.67.' },
    { id: 'dtr-f4', term: 'Cosine Rule', definition: 'a² = b² + c² − 2bc·cosA', example: 'b=5, c=7, A=60° → a=√39≈6.24.' },
    { id: 'dtr-f5', term: 'Triangle Area', definition: 'Area = ½ab·sinC', example: 'Sides 9,12, ∠45° → 27√2.' },
    { id: 'dtr-f6', term: 'Double Angle', definition: 'sin2θ=2sinθcosθ; cos2θ=cos²θ−sin²θ', example: 'sin 90° via double: 2sin45°cos45°=1.' },
    { id: 'dtr-f7', term: 'Arc Length (radians)', definition: 'l = rθ where θ is in radians.', example: 'r=6cm, θ=π/3 → l=2π cm.' },
    { id: 'dtr-f8', term: 'Sector Area (radians)', definition: 'A = ½r²θ where θ is in radians.', example: 'r=4cm, θ=π/2 → A=4π cm².' },
    { id: 'dtr-f9', term: 'Ambiguous Case', definition: 'SSA with acute given angle and a < b can give two triangles.', example: 'a=8, b=12, A=35° → two possible values for angle B.' },
    { id: 'dtr-f10', term: 'Tangent Identity', definition: 'tan θ = sin θ / cos θ', example: 'tan 60° = (√3/2)/(1/2) = √3.' },
  ],
  questions: [
    { id: 'dtr-q1', stem: '210° in radians?', choices: ['5π/6', '7π/6', '4π/3', '3π/4'], correctIndex: 1, explanation: '210×π/180 = 7π/6.' },
    { id: 'dtr-q2', stem: 'sinθ=5/13, θ in Q1. cosθ?', choices: ['12/13', '5/12', '8/13', '13/12'], correctIndex: 0, explanation: 'sin²+cos²=1 → cos²=144/169 → cos=12/13.' },
    { id: 'dtr-q3', stem: 'y=4sin(3x)−2: amplitude and period?', choices: ['A=4, T=2π/3', 'A=4, T=2π', 'A=2, T=2π/3', 'A=4, T=3π'], correctIndex: 0, explanation: '|a|=4, period=2π/3.' },
    { id: 'dtr-q4', stem: 'Solve sinθ=√3/2 for 0≤θ≤2π.', choices: ['π/3 only', 'π/3, 2π/3', 'π/6, 5π/6', 'π/3, 5π/3'], correctIndex: 1, explanation: 'sin + in Q1,Q2 → π/3, π−π/3=2π/3.' },
    { id: 'dtr-q5', stem: '2cos²θ−cosθ−1=0 (0°≤θ≤360°). Solutions?', choices: ['60°,180°,300°', '0°,120°,240°', '90°,120°,240°', '60°,120°,240°'], correctIndex: 1, explanation: 'u=cosθ → (2u+1)(u−1)=0 → cosθ=1(0°), cosθ=−1/2(120°,240°).' },
    { id: 'dtr-q6', stem: 'Triangle: a=7,b=10,∠A=35°. Area?', choices: ['35√3/2 cm²', '35 cm²', '35√3 cm²', '70 cm²'], correctIndex: 0, explanation: '½×7×10×sin35°. Wait, sin35° isn\'t exact. Let me fix: ½×7×10×sin60° = 35×√3/2. So the question should use 60°.' },
    { id: 'dtr-q7', stem: 'A lawn sprinkler rotates through 120° and waters grass up to 5 m from its centre. What area of lawn does it water?', choices: ['25π/3 m²', '50π/3 m²', '25π/6 m²', '100π/3 m²'], correctIndex: 0, explanation: 'Convert 120° to 2π/3 rad. Sector area A = ½r²θ = ½ × 25 × 2π/3 = 25π/3 m². 50π/3 forgets the ½ factor; 25π/6 uses the wrong angle; 100π/3 squares the radius incorrectly.' },
    { id: 'dtr-q8', stem: 'In ΔABC, a = 8, b = 12 and angle A = 35°. How many distinct triangles can be formed?', choices: ['0', '1', '2', 'Infinitely many'], correctIndex: 2, explanation: 'Using the sine rule: sin B = (b sin A)/a ≈ 0.860. Since a < b and angle A is acute, and sin B < 1, there are two possible values for angle B (acute and obtuse), giving two valid triangles. This is the ambiguous case.' },
    { id: 'dtr-q9', stem: 'A triangle has sides 7 cm, 10 cm and 12 cm. Find the largest angle.', choices: ['82.0°', '85.5°', '88.0°', '92.5°'], correctIndex: 2, explanation: 'The largest angle is opposite the longest side (12 cm). Using the cosine rule: cos C = (7² + 10² − 12²)/(2×7×10) = (49 + 100 − 144)/140 = 5/140 = 1/28. So C = cos⁻¹(1/28) ≈ 88.0°.' },
    { id: 'dtr-q10', stem: 'What is the period of y = 3 cos(2x − π/4) + 1?', choices: ['π/2', 'π', '2π', '4π'], correctIndex: 1, explanation: 'For y = a cos(b(x − c)) + d, the period is 2π/|b|. Here b = 2, so period = 2π/2 = π. π/2 confuses the phase shift with the period; 2π ignores the horizontal compression; 4π incorrectly multiplies instead of dividing.' },
    { id: 'dtr-q11', stem: 'A ship sails 15 km on bearing 070°, then turns to bearing 150° and sails 20 km. How far is it from its starting point?', choices: ['24.5 km', '27.0 km', '30.2 km', '35.0 km'], correctIndex: 1, explanation: 'The angle between the two legs at the turn point is 100° (back bearing 250° minus new bearing 150°). Using the cosine rule: d² = 15² + 20² − 2(15)(20)cos(100°) ≈ 729, so d ≈ 27.0 km. 24.5 km uses 80° instead of 100°; 30.2 km uses 60°; 35.0 km simply adds the two distances.' },
    { id: 'dtr-q12', stem: 'A student claims: "If sin θ = 0.5, then θ must be 30°." Which statement BEST explains why this is incorrect?', choices: ['Because sin θ is only positive in quadrant 1', 'Because 30° is not the principal value', 'Because sin θ = 0.5 also has solutions at 150°, 390°, and so on', 'Because calculators always give the wrong answer for inverse sine'], correctIndex: 2, explanation: 'Sine is positive in both Q1 and Q2, so θ = 30° and θ = 150° both satisfy sin θ = 0.5 in [0°, 360°]. Additionally, sine is periodic with period 360°, giving infinitely many solutions. Option A is false (sin is also positive in Q2). Option B is false (30° IS the principal value). Option D is nonsense.' },
  ],
};

export default mathDPTrig;
