import { Topic } from './types';

const mathDPExponents: Topic = {
  id: 'math-dp-exponents',
  subjectId: 'math',
  title: 'Exponents & Logarithms',
  description: 'Laws of indices, definition and laws of logarithms, change of base, natural log, and solving exponential/logarithmic equations.',
  ibLevel: 'DP',
  notes: [
    {
      id: 'eel-n1',
      heading: 'Laws of Indices',
      body: "Exponents (also called indices or powers) give us a compact way to write repeated multiplication. The laws of indices let us simplify and manipulate these expressions quickly.\n\n📌 Definition\nIn the expression aⁿ, the number a is called the base and n is called the exponent (or index).\n    aⁿ = a × a × a × … × a  (n times)\n\n🔑 Laws of Indices\nFor any positive base a (with a ≠ 0, 1) and any real numbers m and n:\n\n    Multiplication:  aᵐ × aⁿ = aᵐ⁺ⁿ\n    Division:        aᵐ ÷ aⁿ = aᵐ⁻ⁿ\n    Power of power:  (aᵐ)ⁿ = aᵐⁿ\n    Power of product: (ab)ⁿ = aⁿbⁿ\n    Power of quotient: (a/b)ⁿ = aⁿ/bⁿ\n\n    Special values:\n    a⁰ = 1   (for any a ≠ 0)\n    a⁻ⁿ = 1/aⁿ\n    a^(1/n) = ⁿ√a\n    a^(m/n) = (ⁿ√a)ᵐ\n\n💡 Worked Example 1 — Simplify (3x²)(2x³y²) / (6x²y)\n\n  Step 1: Multiply the numerators\n    (3x²)(2x³y²) = 6x⁵y²\n\n  Step 2: Divide by the denominator\n    6x⁵y² ÷ 6x²y = x⁵⁻² y²⁻¹ = x³y\n\n  Answer: x³y\n\n💡 Worked Example 2 — Evaluate 9⁴ ÷ 3⁷\n\n  Step 1: Rewrite with the same base\n    9 = 3², so 9⁴ = (3²)⁴ = 3⁸\n\n  Step 2: Apply the division law\n    3⁸ ÷ 3⁷ = 3⁸⁻⁷ = 3¹ = 3\n\n  Answer: 3\n\n📎 Key Points to Remember\n• Index laws only work when the bases are the same — change the base first if needed\n• Take your time and apply one law at a time\n• Work with numbers first, then with algebraic terms\n• A negative exponent means reciprocal, not negative answer\n\n⚠️ Common Mistake\nConfusing aᵐ × aⁿ with (aᵐ)ⁿ. The first adds exponents; the second multiplies them.\n    2³ × 2² = 2⁵ = 32,  but (2³)² = 2⁶ = 64",
    },
    {
      id: 'eel-n2',
      heading: 'Definition and Laws of Logarithms',
      body: "Logarithms are the inverse operation of exponentiation. They answer the question: 'To what power must I raise the base to get this number?'\n\n📌 Definition\nFor a > 0, a ≠ 1, and b > 0:\n    logₐ(b) = c  ⟺  aᶜ = b\n\n    In words: the log of b to base a is the exponent you need on a to produce b.\n\n🔑 Logarithm Laws\nFor any base a > 0, a ≠ 1, and any positive x, y:\n\n    Product law:   logₐ(xy) = logₐ(x) + logₐ(y)\n    Quotient law:  logₐ(x/y) = logₐ(x) − logₐ(y)\n    Power law:     logₐ(xⁿ) = n·logₐ(x)\n\n    Special values:\n    logₐ(1) = 0     (because a⁰ = 1)\n    logₐ(a) = 1     (because a¹ = a)\n\n🔑 Change of Base Formula\n    logₐ(b) = log(b) / log(a)\n\n    You can use any log on the right — common log (base 10) or natural log (base e).\n    This is essential for calculator work when your base is not 10 or e.\n\n💡 Worked Example 1 — Expand log₂(8x³/y)\n\n  Step 1: Apply the quotient law\n    log₂(8x³/y) = log₂(8x³) − log₂(y)\n\n  Step 2: Apply the product law\n    = log₂(8) + log₂(x³) − log₂(y)\n\n  Step 3: Apply the power law and evaluate\n    = 3 + 3·log₂(x) − log₂(y)\n\n  Answer: 3 + 3·log₂(x) − log₂(y)\n\n💡 Worked Example 2 — Evaluate log₅(20) to 3 s.f.\n\n  Step 1: Use change of base\n    log₅(20) = ln(20) / ln(5)\n\n  Step 2: Calculate\n    ≈ 2.996 / 1.609 ≈ 1.86\n\n  Answer: 1.86 (3 s.f.)\n\n📎 Key Points to Remember\n• Logs turn multiplication into addition and division into subtraction\n• The power law lets you bring exponents down in front\n• Change of base is your best friend for calculator evaluation\n• Always check that arguments are positive — log of zero or negatives is undefined\n\n⚠️ Common Mistake\nThinking logₐ(x + y) = logₐ(x) + logₐ(y). This is FALSE.\n    log(2 + 8) = log(10) = 1\n    log(2) + log(8) ≈ 0.301 + 0.903 = 1.204\n    These are not equal! The product law only works for multiplication inside the log.",
    },
    {
      id: 'eel-n3',
      heading: 'Natural Logarithm and Solving Equations',
      body: "The natural logarithm, ln, uses the special number e ≈ 2.718 as its base. Because eˣ and ln(x) are inverse functions, they undo each other — a property that makes solving exponential and logarithmic equations straightforward.\n\n🔑 Natural Logarithm Properties\n    ln(x) = logₑ(x)\n    ln(eˣ) = x     for all real x\n    e^(ln x) = x   for x > 0\n\n💡 Worked Example 1 — Solve 3·2ˣ = 48\n\n  Step 1: Isolate the exponential term\n    2ˣ = 48 ÷ 3 = 16\n\n  Step 2: Express both sides with the same base (or take logs)\n    16 = 2⁴, so 2ˣ = 2⁴\n\n  Step 3: Equate exponents\n    x = 4\n\n  Answer: x = 4\n\n💡 Worked Example 2 — Solve 3ˣ = 45 (give answer to 2 d.p.)\n\n  Step 1: Take ln of both sides\n    ln(3ˣ) = ln(45)\n\n  Step 2: Apply the power law\n    x·ln(3) = ln(45)\n\n  Step 3: Solve for x\n    x = ln(45) / ln(3) ≈ 3.81 / 1.10 ≈ 3.47\n\n  Answer: x ≈ 3.47\n\n💡 Worked Example 3 — Solve log₂(x(x − 2)) = 3\n\n  Step 1: Convert to exponential form\n    x(x − 2) = 2³ = 8\n\n  Step 2: Expand and rearrange\n    x² − 2x − 8 = 0\n\n  Step 3: Factorise\n    (x − 4)(x + 2) = 0\n    x = 4 or x = −2\n\n  Step 4: Check the domain\n    For log₂(x) we need x > 0. For log₂(x − 2) we need x > 2.\n    x = −2 is rejected because it makes both arguments negative.\n\n  Answer: x = 4\n\n📎 Key Points to Remember\n• To solve aˣ = b: take logs of both sides, then isolate x\n• To solve logₐ(expression) = c: rewrite as aᶜ = expression, then solve\n• Always check your final answer against the domain of the original equation\n• Rejected solutions are called extraneous solutions — they are common in log equations\n\n⚠️ Common Mistake\nForgetting to check the domain after solving logarithmic equations.\n    A negative solution might satisfy the algebra but be invalid for the original log expression.\n    Always substitute back and verify every log argument is positive.",
    },
    {
      id: 'eel-n4',
      heading: 'Exponential Growth and Decay',
      body: "Many real-world quantities grow or shrink by a fixed percentage over equal time intervals. These situations are modelled by exponential functions.\n\n📌 Definition\nA quantity changes exponentially when its rate of change is proportional to its current value.\n\n🔑 General Exponential Model\n    y = A·eᵏˣ\n\n    A = initial value (when x = 0)\n    k = growth/decay constant\n    x = time (or other independent variable)\n\n    If k > 0 → exponential growth\n    If k < 0 → exponential decay\n\n🔑 Half-Life Formula\n    T½ = ln(2) / k   (for decay models)\n\n🔑 Continuous Compound Interest\n    A = P·e^(rt)\n\n    P = principal (initial investment)\n    r = annual interest rate (as a decimal)\n    t = time in years\n    A = final amount\n\n💡 Worked Example 1 — Population Growth\nA bacteria population is modelled by N(t) = 200·e^(0.15t), where t is in hours.\nHow many hours until the population reaches 800?\n\n  Step 1: Set up the equation\n    200·e^(0.15t) = 800\n\n  Step 2: Isolate the exponential\n    e^(0.15t) = 4\n\n  Step 3: Take natural logs\n    0.15t = ln(4) ≈ 1.386\n\n  Step 4: Solve for t\n    t ≈ 1.386 / 0.15 ≈ 9.24\n\n  Answer: approximately 9.2 hours\n\n💡 Worked Example 2 — Finding Half-Life\nA radioactive substance decays according to N(t) = N₀·e^(−0.05t). Find its half-life.\n\n  Step 1: Use the half-life formula\n    T½ = ln(2) / k = ln(2) / 0.05\n\n  Step 2: Calculate\n    ≈ 0.693 / 0.05 ≈ 13.9\n\n  Answer: approximately 13.9 years\n\n📎 Key Points to Remember\n• Growth: k > 0, the curve rises steeply to the right\n• Decay: k < 0, the curve falls and approaches the x-axis asymptotically\n• Half-life is constant — it does not depend on the initial amount\n• In compound interest, e^(rt) gives the continuous compounding factor\n\n⚠️ Common Mistake\nUsing the wrong sign for k.\n    If a population is decreasing, k must be negative.\n    A positive k with 'decay' in the word problem is a contradiction — check your setup!",
    },
    {
      id: 'eel-n5',
      heading: 'Logarithmic Scales and Real-World Models',
      body: "Many natural phenomena span enormous ranges — earthquake energy, sound intensity, acidity. Linear scales become impractical, so scientists use logarithmic scales where equal steps represent equal ratios, not equal amounts.\n\n📌 Why Log Scales?\nOn a linear scale, the distance from 1 to 2 is the same as from 1000 to 1001.\nOn a log scale, the distance from 1 to 10 equals the distance from 10 to 100.\nThis compresses huge ranges into manageable numbers.\n\n🔑 Common Logarithmic Scales\n\n    Richter scale (earthquakes):\n        R = log(A / A₀)\n        A difference of 1 means 10× more wave amplitude\n        A difference of 2 means 100× more wave amplitude\n\n    Decibel scale (sound):\n        L = 10·log(I / I₀)\n        Every 10 dB increase means 10× more intensity\n\n    pH scale (acidity):\n        pH = −log[H⁺]\n        Lower pH means higher acidity\n        A difference of 1 pH unit means 10× difference in [H⁺]\n\n💡 Worked Example 1 — Richter Scale\nAn earthquake measures 6.0 on the Richter scale. Another measures 4.0.\nHow many times greater is the wave amplitude?\n\n  Step 1: Find the difference\n    6.0 − 4.0 = 2\n\n  Step 2: Convert to amplitude ratio\n    Amplitude ratio = 10² = 100\n\n  Answer: 100 times greater\n\n💡 Worked Example 2 — Sound Intensity\nA concert speaker produces 90 dB. Normal conversation is 60 dB.\nHow many times more intense is the concert sound?\n\n  Step 1: Find the decibel difference\n    90 − 60 = 30 dB\n\n  Step 2: Use the decibel formula\n    30 = 10·log(I_concert / I_conversation)\n    3 = log(I_concert / I_conversation)\n\n  Step 3: Convert from log form\n    I_concert / I_conversation = 10³ = 1000\n\n  Answer: 1000 times more intense\n\n📎 Key Points to Remember\n• On any log scale, equal differences mean equal ratios, not equal amounts\n• A change of +1 on a base-10 log scale always means ×10\n• pH is reverse: lower numbers mean higher concentration\n• Log scales are used because human perception itself is often logarithmic\n\n⚠️ Common Mistake\nTreating log-scale differences as linear differences.\n    A magnitude 8 earthquake is NOT 'twice as strong' as magnitude 4.\n    The difference is 4 units, so the amplitude ratio is 10⁴ = 10 000×.",
    },
  ],
  flashcards: [
    { id: 'eel-f1', term: 'Definition of log', definition: 'logₐ(b)=c ⟺ aᶜ=b', example: 'log₂(8)=3 because 2³=8' },
    { id: 'eel-f2', term: 'Product law', definition: 'logₐ(xy) = logₐ(x) + logₐ(y)', example: 'log₃(9×27) = 2+3 = 5' },
    { id: 'eel-f3', term: 'Quotient law', definition: 'logₐ(x/y) = logₐ(x) − logₐ(y)', example: 'log₂(32/4) = 5−2 = 3' },
    { id: 'eel-f4', term: 'Power law', definition: 'logₐ(xⁿ) = n·logₐ(x)', example: 'log₂(8³) = 3×3 = 9' },
    { id: 'eel-f5', term: 'Change of base', definition: 'logₐ(b) = log(b)/log(a)', example: 'log₅(20) = ln20/ln5 ≈ 1.861' },
    { id: 'eel-f6', term: 'Half-life', definition: 'T½ = ln2/k for N(t)=N₀e^(−kt)', example: 'k=0.1 → T½≈6.93 years' },
    { id: 'eel-f7', term: 'Logarithmic scale', definition: 'A scale where equal steps represent equal ratios, not equal differences.', example: 'Richter scale: magnitude 6 is 10× stronger than 5 in wave amplitude.' },
    { id: 'eel-f8', term: 'Decibel level', definition: 'L = 10 log(I/I₀) where I₀ is the threshold of hearing.', example: '80 dB is 10× more intense than 70 dB.' },
    { id: 'eel-f9', term: 'Solving same-base exponentials', definition: 'If aˣ = aʸ then x = y (for a>0, a≠1).', example: '2^(3x−1) = 2⁵ → 3x−1=5 → x=2.' },
    { id: 'eel-f10', term: 'Common log misconception', definition: 'log(x+y) ≠ log(x) + log(y). The product law only applies to multiplication inside the log.', example: 'log(2+8)=log10=1, but log2+log8≈0.301+0.903=1.204. Not equal!' },
  ],
  questions: [
    { id: 'eel-q1', stem: '27^(2/3) = ?', choices: ['3', '6', '9', '18'], correctIndex: 2, explanation: '(∛27)² = 3² = 9.' },
    { id: 'eel-q2', stem: 'log₂(64) = ?', choices: ['4', '5', '6', '8'], correctIndex: 2, explanation: '2⁶=64.' },
    { id: 'eel-q3', stem: 'log(12) in terms of log(2), log(3):', choices: ['log2+log3', '2log2+log3', 'log2+2log3', '3log2−log3'], correctIndex: 1, explanation: '12=2²×3 → 2log2+log3.' },
    { id: 'eel-q4', stem: '3ˣ=45 → x≈?', choices: ['2.46', '3.09', '3.47', '3.91'], correctIndex: 2, explanation: 'ln45/ln3≈3.47.' },
    { id: 'eel-q5', stem: 'log₃(x)+log₃(x−6)=3 → x=?', choices: ['7', '9', '12', '27'], correctIndex: 1, explanation: 'x(x−6)=27 → x²−6x−27=0 → x=9.' },
    { id: 'eel-q6', stem: 'e^(ln 3) + ln(e³) = ?', choices: ['0', '3', '6', '9'], correctIndex: 2, explanation: '3 + 3 = 6.' },
    { id: 'eel-q7', stem: 'A concert speaker produces sound at 90 dB. A normal conversation is 60 dB. How many times more intense is the concert sound?', choices: ['3', '30', '100', '1000'], correctIndex: 3, explanation: 'Decibels use L = 10 log(I/I₀). A 30 dB difference means 10^(30/10) = 10³ = 1000× more intense. Each 10 dB step is a 10× multiplier, so three steps = 10×10×10 = 1000.' },
    { id: 'eel-q8', stem: 'Which of the following statements is ALWAYS true for a > 0, a ≠ 1 and x, y > 0?', choices: ['logₐ(x+y) = logₐ(x) + logₐ(y)', 'logₐ(x·y) = logₐ(x)·logₐ(y)', 'logₐ(x/y) = logₐ(x) − logₐ(y)', 'logₐ(xⁿ) = (logₐ x)ⁿ'], correctIndex: 2, explanation: 'The quotient law states logₐ(x/y) = logₐ(x) − logₐ(y). Choice A confuses sum with product; the product law says log(xy)=log(x)+log(y). Choice B confuses log of a product with product of logs. Choice D confuses log of a power with power of a log.' },
    { id: 'eel-q9', stem: 'An earthquake measures 6.0 on the Richter scale. Another measures 4.0. How many times greater is the wave amplitude of the larger earthquake?', choices: ['2', '10', '100', '1000'], correctIndex: 2, explanation: 'Richter scale: R = log(A/A₀). Difference = 6−4 = 2. Amplitude ratio = 10² = 100. Each whole number step on the Richter scale represents a 10-fold increase in wave amplitude.' },
    { id: 'eel-q10', stem: 'Solve for x: 5^(2x−1) = 125.', choices: ['1', '2', '3', '4'], correctIndex: 1, explanation: 'Write 125 as 5³. Since the bases are equal: 2x−1 = 3 → 2x = 4 → x = 2.' },
    { id: 'eel-q11', stem: 'The pH of a solution is defined as pH = −log[H⁺], where [H⁺] is hydrogen ion concentration. If lemon juice has [H⁺] = 1×10⁻² and milk has [H⁺] = 1×10⁻⁶, how many times more acidic is the lemon juice?', choices: ['4', '10', '100', '10000'], correctIndex: 3, explanation: 'pH of lemon juice = −log(10⁻²) = 2. pH of milk = −log(10⁻⁶) = 6. A difference of 4 pH units means 10⁴ = 10000× more acidic. Alternatively, ratio of [H⁺] = 10⁻²/10⁻⁶ = 10⁴ = 10000.' },
    { id: 'eel-q12', stem: 'Simplify (8x⁶)^(2/3).', choices: ['4x⁴', '12x⁴', '4x⁸', '16x¹²'], correctIndex: 0, explanation: '8^(2/3) = (∛8)² = 2² = 4. (x⁶)^(2/3) = x^(6×2/3) = x⁴. So the result is 4x⁴. A common mistake is to multiply 8×2/3=16/3 or to add exponents instead of multiplying.' },
  ],
};

export default mathDPExponents;
