import { Topic } from './types';

const mathDPQuadratics: Topic = {
  id: 'math-dp-quadratics',
  subjectId: 'math',
  title: 'Quadratic Functions & Equations',
  description: "Standard, vertex, and factored forms; completing the square; quadratic formula; discriminant; Vieta's formulas; inequalities; optimisation.",
  ibLevel: 'DP',
  notes: [
    {
      id: 'qua-n1',
      heading: 'Forms of a Quadratic',
      body: 'A quadratic function is any function of the form f(x) = ax² + bx + c where a ≠ 0. Its graph is a parabola. The way you write the equation reveals different features instantly.\n\n📌 Standard Form\n    f(x) = ax² + bx + c\n• The y-intercept is (0, c) — just substitute x = 0.\n• The axis of symmetry is x = −b/(2a).\n• The vertex has x-coordinate −b/(2a).\n\n📌 Vertex Form\n    f(x) = a(x − h)² + k\n• The vertex is at the point (h, k).\n• The axis of symmetry is x = h.\n• If a > 0, the parabola opens upward (∪ shape) and the vertex is a minimum.\n• If a < 0, the parabola opens downward (∩ shape) and the vertex is a maximum.\n\n📌 Factored Form\n    f(x) = a(x − p)(x − q)\n• The x-intercepts (roots) are at x = p and x = q.\n• The axis of symmetry is exactly halfway between the roots: x = (p + q)/2.\n• Substitute x = 0 to find the y-intercept: f(0) = apq.\n\n💡 Worked Example — Finding the Vertex from Standard Form\nFind the vertex of f(x) = 2x² − 8x + 1.\n\n  Step 1: Identify a and b\n    a = 2,  b = −8\n\n  Step 2: Find the axis of symmetry\n    x = −b/(2a) = −(−8)/(2 × 2) = 8/4 = 2\n\n  Step 3: Find the y-coordinate of the vertex\n    f(2) = 2(2)² − 8(2) + 1 = 8 − 16 + 1 = −7\n\n  Answer: The vertex is (2, −7).\n\n💡 Worked Example — Converting Factored to Standard Form\nFind the y-intercept of f(x) = −3(x − 2)(x + 5).\n\n  Step 1: Expand the brackets\n    f(x) = −3(x² + 5x − 2x − 10) = −3(x² + 3x − 10)\n\n  Step 2: Distribute the −3\n    f(x) = −3x² − 9x + 30\n\n  Answer: The y-intercept is 30.\n\n📎 Key Points to Remember\n• a controls width and direction: |a| > 1 → narrower; |a| < 1 → wider.\n• The three forms are equivalent — you can always expand or factorise to switch between them.\n• Vertex form is best for graphing; factored form is best for finding roots.\n\n⚠️ Common Mistake\nMixing up the sign in vertex form. In f(x) = a(x − h)² + k, the vertex is (h, k), NOT (−h, k). For example, f(x) = 3(x + 2)² − 5 has vertex (−2, −5).',
    },
    {
      id: 'qua-n2',
      heading: 'Solving Quadratics',
      body: 'There are three main ways to solve a quadratic equation ax² + bx + c = 0: factorising, completing the square, and the quadratic formula. Each has its own best-use case.\n\n📌 Method 1: Factorising (Null Factor Law)\nIf you can write ax² + bx + c as a product of two linear factors, then:\n    (px + q)(rx + s) = 0  →  px + q = 0  or  rx + s = 0\nThis is the fastest method when the quadratic factors neatly.\n\n📌 Method 2: Completing the Square\nRewrite ax² + bx + c in the form a(x + h)² + k.\nWhen a = 1:\n    x² + bx + c = (x + b/2)² − (b²/4) + c\nWhen a ≠ 1, factor a out from the x-terms first.\n\n📌 Method 3: The Quadratic Formula\nFor any quadratic ax² + bx + c = 0 with a ≠ 0:\n    x = (−b ± √(b² − 4ac)) / (2a)\n\n🔑 The Discriminant\nThe expression under the square root is called the discriminant:\n    Δ = b² − 4ac\n• Δ > 0  →  two distinct real roots\n• Δ = 0  →  one repeated real root (the parabola touches the x-axis)\n• Δ < 0  →  no real roots (the parabola does not cross the x-axis)\n\n💡 Worked Example — Using the Quadratic Formula\nSolve 2x² − 5x − 3 = 0.\n\n  Step 1: Identify a, b, c\n    a = 2,  b = −5,  c = −3\n\n  Step 2: Calculate the discriminant\n    Δ = (−5)² − 4(2)(−3) = 25 + 24 = 49\n\n  Step 3: Apply the formula\n    x = (5 ± √49) / 4 = (5 ± 7) / 4\n\n  Step 4: Find both solutions\n    x = (5 + 7)/4 = 12/4 = 3\n    x = (5 − 7)/4 = −2/4 = −1/2\n\n  Answer: x = 3  or  x = −1/2\n\n💡 Worked Example — Completing the Square\nWrite x² + 6x + 5 in the form (x + h)² + k.\n\n  Step 1: Take half the coefficient of x and square it\n    (6/2)² = 9\n\n  Step 2: Add and subtract this value inside the expression\n    x² + 6x + 5 = (x² + 6x + 9) + 5 − 9\n\n  Step 3: Factor the perfect square\n    = (x + 3)² − 4\n\n  Answer: (x + 3)² − 4, so the vertex is (−3, −4).\n\n📎 Key Points to Remember\n• Always try factorising first — it is the quickest method when it works.\n• Completing the square is essential for deriving the quadratic formula and for graphing.\n• The quadratic formula always works, even when factorising is difficult.\n• If a quadratic has no real roots, you can still find complex roots using the same formula.\n\n⚠️ Common Mistake\nDividing both sides of an equation by x. For example, solving x² = 5x by dividing by x gives x = 5 and loses the solution x = 0. Always rearrange to make the RHS zero before factorising.',
    },
    {
      id: 'qua-n3',
      heading: "Vieta's Formulas",
      body: "When a quadratic equation has roots, there is a beautiful relationship between the coefficients and the roots — even if you never find the roots explicitly.\n\n📌 Definition\nFor the quadratic ax² + bx + c = 0 with roots α and β:\n    Sum of roots:     α + β = −b/a\n    Product of roots: αβ = c/a\n\nThese are called Vieta's formulas (or the sum-and-product of roots).\n\n🔑 Why They Matter\n• Check your answers: if you solve a quadratic, the sum and product of your solutions should match −b/a and c/a.\n• Form a quadratic from its roots: if roots are α and β, the monic quadratic is x² − (α + β)x + αβ = 0.\n• Solve problems without finding roots: many symmetric expressions in α and β can be evaluated directly.\n\n💡 Worked Example — Forming a Quadratic from Roots\nFind a quadratic equation with roots 2 and −5.\n\n  Step 1: Find the sum and product\n    Sum = 2 + (−5) = −3\n    Product = 2 × (−5) = −10\n\n  Step 2: Write the monic quadratic\n    x² − (sum)x + (product) = 0\n    x² − (−3)x + (−10) = 0\n\n  Step 3: Simplify\n    x² + 3x − 10 = 0\n\n  Answer: x² + 3x − 10 = 0\n\n💡 Worked Example — Evaluating without Finding Roots\nIf α and β are roots of 2x² − 7x + 3 = 0, find α² + β².\n\n  Step 1: Use Vieta's formulas\n    α + β = −(−7)/2 = 7/2\n    αβ = 3/2\n\n  Step 2: Rewrite α² + β² using the identity\n    α² + β² = (α + β)² − 2αβ\n\n  Step 3: Substitute\n    = (7/2)² − 2(3/2)\n    = 49/4 − 3\n    = 49/4 − 12/4\n    = 37/4\n\n  Answer: α² + β² = 37/4\n\n📎 Key Points to Remember\n• Vieta's formulas work for any quadratic, even when the roots are complex.\n• For a monic quadratic (a = 1), the formulas simplify to: sum = −b, product = c.\n• Common symmetric expressions: α² + β² = (α + β)² − 2αβ and 1/α + 1/β = (α + β)/(αβ).\n\n⚠️ Common Mistake\nForgetting the minus sign in the sum formula. The sum of roots equals −b/a, not b/a. If the quadratic is x² − 5x + 6 = 0, the sum of roots is 5 (not −5) because −b/a = −(−5)/1 = 5.",
    },
    {
      id: 'qua-n4',
      heading: 'Inequalities and Optimisation',
      body: 'Quadratic inequalities and optimisation problems appear constantly in IB exams. The key is understanding how the parabola shape determines where the expression is positive or negative.\n\n📌 Solving Quadratic Inequalities\nTo solve ax² + bx + c > 0 (or < 0, ≥ 0, ≤ 0):\n\n  1. Find the roots by solving ax² + bx + c = 0.\n  2. Sketch the parabola using the sign of a.\n  3. Read the solution from the graph.\n\n🔑 The Sign Rule\n• If a > 0 (parabola opens upward):\n    ax² + bx + c > 0  →  outside the roots (x < smaller root or x > larger root)\n    ax² + bx + c < 0  →  between the roots\n• If a < 0 (parabola opens downward), the inequalities reverse.\n\n📌 Optimisation with Quadratics\nFor f(x) = ax² + bx + c, the vertex gives the extreme value:\n• If a > 0, the minimum value occurs at x = −b/(2a).\n• If a < 0, the maximum value occurs at x = −b/(2a).\n\n💡 Worked Example — Quadratic Inequality\nSolve x² − x − 12 < 0.\n\n  Step 1: Find the roots\n    x² − x − 12 = 0\n    (x − 4)(x + 3) = 0\n    x = 4  or  x = −3\n\n  Step 2: Determine the shape\n    a = 1 > 0, so the parabola opens upward.\n\n  Step 3: Read the solution\n    We want where the parabola is below the x-axis — between the roots.\n\n  Answer: −3 < x < 4\n\n💡 Worked Example — Optimisation\nA ball is thrown upward and its height after t seconds is h(t) = −5t² + 20t + 1 metres. Find the maximum height and when it occurs.\n\n  Step 1: Identify a and b\n    a = −5,  b = 20\n\n  Step 2: Find the time at the vertex\n    t = −b/(2a) = −20/(2 × −5) = −20/(−10) = 2 seconds\n\n  Step 3: Find the maximum height\n    h(2) = −5(2)² + 20(2) + 1 = −20 + 40 + 1 = 21 metres\n\n  Answer: Maximum height is 21 m at t = 2 s.\n\n📎 Key Points to Remember\n• Always make the RHS zero before solving an inequality.\n• When multiplying or dividing an inequality by a negative number, flip the inequality sign.\n• For optimisation, always check that your answer makes sense in the real-world context (e.g., time cannot be negative).\n• The vertex formula x = −b/(2a) is faster than completing the square for finding maxima/minima.\n\n⚠️ Common Mistake\nWriting the solution to x² − x − 12 > 0 as x < −3 and x > 4 (using \"and\" instead of \"or\"). These are two separate intervals that do not overlap, so the correct connective is \"or\". In interval notation: (−∞, −3) ∪ (4, ∞).',
    },
    {
      id: 'qua-n5',
      heading: 'Positive and Negative Definite Quadratics',
      body: 'Some quadratics are always positive or always negative — they never cross the x-axis. Recognising these quickly saves time and prevents sign errors.\n\n📌 Definitions\n• A quadratic is positive definite when ax² + bx + c > 0 for ALL real x.\n• A quadratic is negative definite when ax² + bx + c < 0 for ALL real x.\n\n🔑 Test for Definiteness\n    Positive definite  ↔  a > 0  AND  Δ < 0\n    Negative definite  ↔  a < 0  AND  Δ < 0\n\nWhy does this work? The discriminant Δ < 0 means there are no real roots, so the parabola never touches the x-axis. The sign of a then tells you whether the entire graph is above (a > 0) or below (a < 0) the x-axis.\n\n💡 Worked Example — Testing for Positive Definite\nShow that x² + 2x + 3 is positive definite.\n\n  Step 1: Check the coefficient of x²\n    a = 1 > 0  →  parabola opens upward\n\n  Step 2: Calculate the discriminant\n    Δ = b² − 4ac = (2)² − 4(1)(3) = 4 − 12 = −8\n\n  Step 3: Apply the test\n    a > 0 and Δ < 0  →  positive definite\n\n  Answer: x² + 2x + 3 > 0 for all real x.\n\n💡 Worked Example — Finding a Parameter for Definiteness\nFor what values of k is x² − 4x + k positive definite?\n\n  Step 1: Identify a, b, c\n    a = 1,  b = −4,  c = k\n\n  Step 2: Apply the positive definite condition\n    Need a > 0 (true, since a = 1) AND Δ < 0\n\n  Step 3: Solve Δ < 0\n    Δ = (−4)² − 4(1)(k) = 16 − 4k\n    16 − 4k < 0\n    16 < 4k\n    k > 4\n\n  Answer: The quadratic is positive definite when k > 4.\n\n📎 Key Points to Remember\n• The phrase \"definite\" means the quadratic has a definite sign — it never changes.\n• If Δ ≥ 0, the quadratic is neither positive nor negative definite (it crosses or touches the x-axis).\n• Positive definite quadratics are useful for proving inequalities and showing expressions are always positive.\n• Negative definite quadratics are less common but appear in certain optimisation and proof problems.\n\n⚠️ Common Mistake\nChecking only Δ < 0 without checking the sign of a. A quadratic with a < 0 and Δ < 0 is negative definite, not positive definite. Both conditions must be verified.',
    },
  ],
  flashcards: [
    { id: 'qua-f1', term: 'Standard form', definition: 'f(x)=ax²+bx+c', example: '2x²−4x+1: y-int=1, axis x=1' },
    { id: 'qua-f2', term: 'Vertex form', definition: 'a(x−h)²+k; vertex (h,k)', example: '3(x−2)²−5: vertex (2,−5)' },
    { id: 'qua-f3', term: 'Quadratic formula', definition: 'x=(−b±√Δ)/(2a)', example: 'x²−5x+6→x=2 or 3' },
    { id: 'qua-f4', term: 'Discriminant', definition: 'Δ=b²−4ac determines root nature', example: 'x²−6x+9: Δ=0→repeated root x=3' },
    { id: 'qua-f5', term: 'Completing the square', definition: 'Rewrite ax²+bx+c as a(x+h)²+k to reveal the vertex and solve.', example: 'x²+6x+5=(x+3)²−4; vertex (−3,−4).' },
    { id: 'qua-f6', term: 'Axis of symmetry', definition: 'The vertical line through the vertex: x=−b/(2a).', example: 'For x²−4x+3, axis is x=2.' },
    { id: 'qua-f7', term: 'Positive / Negative definite', definition: 'Always positive (a>0, Δ<0) or always negative (a<0, Δ<0).', example: 'x²+2x+3 has Δ=−8<0, a>0 → always positive.' },
    { id: 'qua-f8', term: "Vieta's sum and product", definition: 'For roots α, β of ax²+bx+c=0: α+β=−b/a and αβ=c/a.', example: 'x²−7x+10=0: sum=7, product=10 → roots 2 and 5.' },
  ],
  questions: [
    { id: 'qua-q1', stem: 'Solve x²−5x+6=0.', choices: ['1,6', '2,3', '−2,−3', '−1,6'], correctIndex: 1, explanation: '(x−2)(x−3)=0.' },
    { id: 'qua-q2', stem: 'Δ of 2x²−3x+5=0?', choices: ['31, 2 real', '−31, no real', '49, 2 real', '−49, no real'], correctIndex: 1, explanation: '9−40=−31<0.' },
    { id: 'qua-q3', stem: 'Vertex form of x²−6x+7:', choices: ['(x−3)²−2', '(x+3)²−2', '(x−3)²+2', '(x−3)²−16'], correctIndex: 0, explanation: '(x−3)²−9+7=(x−3)²−2.' },
    { id: 'qua-q4', stem: 'Max of f(x)=−2x²+8x−3?', choices: ['5 at x=2', '5 at x=−2', '−3 at x=0', '3 at x=2'], correctIndex: 0, explanation: 'x=−b/2a=2. f(2)=5.' },
    { id: 'qua-q5', stem: 'x²−x−12<0 solution:', choices: ['x<−3 or x>4', '−3<x<4', '−4<x<3', 'x<−4 or x>3'], correctIndex: 1, explanation: '(x−4)(x+3)<0 → between roots.' },
    { id: 'qua-q6', stem: 'Rectangle perimeter 40m. Max area?', choices: ['100 m²', '200 m²', '80 m²', '150 m²'], correctIndex: 0, explanation: 'A=x(20−x); max at x=10: 100 m².' },
    { id: 'qua-q7', stem: 'Which condition guarantees that ax²+bx+c is positive for all real x?', choices: ['a>0', 'Δ<0', 'a>0 and Δ<0', 'a<0 and Δ<0'], correctIndex: 2, explanation: 'The parabola must open upward (a>0) AND never touch the x-axis (Δ<0). Together these make the quadratic positive definite.' },
    { id: 'qua-q8', stem: 'By completing the square, write 2x²−8x+5 in the form a(x−h)²+k.', choices: ['2(x−2)²−3', '2(x−4)²−27', '(x−2)²−3', '2(x−2)²+5'], correctIndex: 0, explanation: 'Factor out 2: 2(x²−4x)+5 = 2[(x−2)²−4]+5 = 2(x−2)²−8+5 = 2(x−2)²−3.' },
    { id: 'qua-q9', stem: 'A ball is thrown upward. Its height after t seconds is h(t)=−4t²+16t+3 metres. What is the maximum height reached?', choices: ['16 m', '19 m', '20 m', '23 m'], correctIndex: 1, explanation: 'The maximum occurs at t=−b/(2a)=−16/(−8)=2s. Substituting: h(2)=−4(4)+16(2)+3=−16+32+3=19m.' },
    { id: 'qua-q10', stem: 'A quadratic has roots 3 and −2, and its y-intercept is −12. Find its equation.', choices: ['y=2x²−2x−12', 'y=x²−x−6', 'y=2x²+2x−12', 'y=x²+x−6'], correctIndex: 0, explanation: 'Factored form: y=a(x−3)(x+2). At x=0, y=a(−3)(2)=−6a=−12 → a=2. Expanding: y=2(x²−x−6)=2x²−2x−12.' },
    { id: 'qua-q11', stem: 'For what values of k is x²−4x+k positive for all real x?', choices: ['k>4', 'k<4', 'k≥4', 'k≤4'], correctIndex: 0, explanation: 'Need Δ<0. Δ=(−4)²−4(1)(k)=16−4k<0 → 4k>16 → k>4. When k>4, the parabola opens upward and never touches the x-axis, so it is always positive.' },
    { id: 'qua-q12', stem: 'The line y=3x+c is tangent to the parabola y=x²+5x+2. Find c.', choices: ['1', '2', '3', '4'], correctIndex: 0, explanation: 'Set equal: x²+5x+2=3x+c → x²+2x+(2−c)=0. For tangency, Δ=0. Δ=4−4(2−c)=4c−4=0 → c=1.' },
  ],
};

export default mathDPQuadratics;
