// GENERATED by scripts/generate-registry.ts — do not edit by hand.
//
// Paper CONTENT (questions + mark schemes). SERVER-ONLY, and premium by definition: sets 2+ are the
// gated surface (docs/premium-content-protection-plan.md §4.4). The only legitimate importer is the
// premium content API; nothing under src/app/** may import it.
import type { Paper } from './types';
import { paperSchema } from './schema';

// bio-ks3 practice sets
import bio_ks3_bio_ks3_set_1_json from './data/papers/bio-ks3/bio-ks3-set-1.json';
import bio_ks3_bio_ks3_set_2_json from './data/papers/bio-ks3/bio-ks3-set-2.json';
// chem-ks3 practice sets
import chem_ks3_chem_ks3_set_1_json from './data/papers/chem-ks3/chem-ks3-set-1.json';
import chem_ks3_chem_ks3_set_2_json from './data/papers/chem-ks3/chem-ks3-set-2.json';
// chin-ks3 practice sets
import chin_ks3_chin_ks3_set_1_json from './data/papers/chin-ks3/chin-ks3-set-1.json';
import chin_ks3_chin_ks3_set_2_json from './data/papers/chin-ks3/chin-ks3-set-2.json';
// eng-ks3 practice sets
import eng_ks3_eng_ks3_set_1_json from './data/papers/eng-ks3/eng-ks3-set-1.json';
import eng_ks3_eng_ks3_set_2_json from './data/papers/eng-ks3/eng-ks3-set-2.json';
// geog-ks3 practice sets
import geog_ks3_geog_ks3_set_1_json from './data/papers/geog-ks3/geog-ks3-set-1.json';
import geog_ks3_geog_ks3_set_2_json from './data/papers/geog-ks3/geog-ks3-set-2.json';
// germ-ks3 practice sets
import germ_ks3_germ_ks3_set_1_json from './data/papers/germ-ks3/germ-ks3-set-1.json';
import germ_ks3_germ_ks3_set_2_json from './data/papers/germ-ks3/germ-ks3-set-2.json';
// hist-ks3 practice sets
import hist_ks3_hist_ks3_set_1_json from './data/papers/hist-ks3/hist-ks3-set-1.json';
import hist_ks3_hist_ks3_set_2_json from './data/papers/hist-ks3/hist-ks3-set-2.json';
// ict-ks3 practice sets
import ict_ks3_ict_ks3_set_1_json from './data/papers/ict-ks3/ict-ks3-set-1.json';
import ict_ks3_ict_ks3_set_2_json from './data/papers/ict-ks3/ict-ks3-set-2.json';
// math-dp-ai practice sets
import math_dp_ai_math_dp_ai_set_1_json from './data/papers/math-dp-ai/math-dp-ai-set-1.json';
import math_dp_ai_math_dp_ai_set_2_json from './data/papers/math-dp-ai/math-dp-ai-set-2.json';
// math-igcse practice sets
import math_igcse_math_igcse_set_1_json from './data/papers/math-igcse/math-igcse-set-1.json';
import math_igcse_math_igcse_set_2_json from './data/papers/math-igcse/math-igcse-set-2.json';
import math_igcse_math_igcse_set_3_json from './data/papers/math-igcse/math-igcse-set-3.json';
// math-y7 practice sets
import math_y7_math_y7_set_1_json from './data/papers/math-y7/math-y7-set-1.json';
import math_y7_math_y7_set_2_json from './data/papers/math-y7/math-y7-set-2.json';
// math-y8 practice sets
import math_y8_math_y8_set_1_json from './data/papers/math-y8/math-y8-set-1.json';
import math_y8_math_y8_set_2_json from './data/papers/math-y8/math-y8-set-2.json';
// math-y9 practice sets
import math_y9_math_y9_set_1_json from './data/papers/math-y9/math-y9-set-1.json';
import math_y9_math_y9_set_2_json from './data/papers/math-y9/math-y9-set-2.json';
// phys-ks3 practice sets
import phys_ks3_phys_ks3_set_1_json from './data/papers/phys-ks3/phys-ks3-set-1.json';
import phys_ks3_phys_ks3_set_2_json from './data/papers/phys-ks3/phys-ks3-set-2.json';

const bio_ks3_bio_ks3_set_1: Paper = paperSchema.parse(bio_ks3_bio_ks3_set_1_json);
const bio_ks3_bio_ks3_set_2: Paper = paperSchema.parse(bio_ks3_bio_ks3_set_2_json);
const chem_ks3_chem_ks3_set_1: Paper = paperSchema.parse(chem_ks3_chem_ks3_set_1_json);
const chem_ks3_chem_ks3_set_2: Paper = paperSchema.parse(chem_ks3_chem_ks3_set_2_json);
const chin_ks3_chin_ks3_set_1: Paper = paperSchema.parse(chin_ks3_chin_ks3_set_1_json);
const chin_ks3_chin_ks3_set_2: Paper = paperSchema.parse(chin_ks3_chin_ks3_set_2_json);
const eng_ks3_eng_ks3_set_1: Paper = paperSchema.parse(eng_ks3_eng_ks3_set_1_json);
const eng_ks3_eng_ks3_set_2: Paper = paperSchema.parse(eng_ks3_eng_ks3_set_2_json);
const geog_ks3_geog_ks3_set_1: Paper = paperSchema.parse(geog_ks3_geog_ks3_set_1_json);
const geog_ks3_geog_ks3_set_2: Paper = paperSchema.parse(geog_ks3_geog_ks3_set_2_json);
const germ_ks3_germ_ks3_set_1: Paper = paperSchema.parse(germ_ks3_germ_ks3_set_1_json);
const germ_ks3_germ_ks3_set_2: Paper = paperSchema.parse(germ_ks3_germ_ks3_set_2_json);
const hist_ks3_hist_ks3_set_1: Paper = paperSchema.parse(hist_ks3_hist_ks3_set_1_json);
const hist_ks3_hist_ks3_set_2: Paper = paperSchema.parse(hist_ks3_hist_ks3_set_2_json);
const ict_ks3_ict_ks3_set_1: Paper = paperSchema.parse(ict_ks3_ict_ks3_set_1_json);
const ict_ks3_ict_ks3_set_2: Paper = paperSchema.parse(ict_ks3_ict_ks3_set_2_json);
const math_dp_ai_math_dp_ai_set_1: Paper = paperSchema.parse(math_dp_ai_math_dp_ai_set_1_json);
const math_dp_ai_math_dp_ai_set_2: Paper = paperSchema.parse(math_dp_ai_math_dp_ai_set_2_json);
const math_igcse_math_igcse_set_1: Paper = paperSchema.parse(math_igcse_math_igcse_set_1_json);
const math_igcse_math_igcse_set_2: Paper = paperSchema.parse(math_igcse_math_igcse_set_2_json);
const math_igcse_math_igcse_set_3: Paper = paperSchema.parse(math_igcse_math_igcse_set_3_json);
const math_y7_math_y7_set_1: Paper = paperSchema.parse(math_y7_math_y7_set_1_json);
const math_y7_math_y7_set_2: Paper = paperSchema.parse(math_y7_math_y7_set_2_json);
const math_y8_math_y8_set_1: Paper = paperSchema.parse(math_y8_math_y8_set_1_json);
const math_y8_math_y8_set_2: Paper = paperSchema.parse(math_y8_math_y8_set_2_json);
const math_y9_math_y9_set_1: Paper = paperSchema.parse(math_y9_math_y9_set_1_json);
const math_y9_math_y9_set_2: Paper = paperSchema.parse(math_y9_math_y9_set_2_json);
const phys_ks3_phys_ks3_set_1: Paper = paperSchema.parse(phys_ks3_phys_ks3_set_1_json);
const phys_ks3_phys_ks3_set_2: Paper = paperSchema.parse(phys_ks3_phys_ks3_set_2_json);

const papers: Paper[] = [bio_ks3_bio_ks3_set_1, bio_ks3_bio_ks3_set_2, chem_ks3_chem_ks3_set_1, chem_ks3_chem_ks3_set_2, chin_ks3_chin_ks3_set_1, chin_ks3_chin_ks3_set_2, eng_ks3_eng_ks3_set_1, eng_ks3_eng_ks3_set_2, geog_ks3_geog_ks3_set_1, geog_ks3_geog_ks3_set_2, germ_ks3_germ_ks3_set_1, germ_ks3_germ_ks3_set_2, hist_ks3_hist_ks3_set_1, hist_ks3_hist_ks3_set_2, ict_ks3_ict_ks3_set_1, ict_ks3_ict_ks3_set_2, math_dp_ai_math_dp_ai_set_1, math_dp_ai_math_dp_ai_set_2, math_igcse_math_igcse_set_1, math_igcse_math_igcse_set_2, math_igcse_math_igcse_set_3, math_y7_math_y7_set_1, math_y7_math_y7_set_2, math_y8_math_y8_set_1, math_y8_math_y8_set_2, math_y9_math_y9_set_1, math_y9_math_y9_set_2, phys_ks3_phys_ks3_set_1, phys_ks3_phys_ks3_set_2];

export function getAllPapersContent(): Paper[] {
  return papers;
}

export function getPapersForCourseContent(courseId: string): Paper[] {
  return papers.filter((p) => p.courseId === courseId);
}

export function getPaperContent(courseId: string, paperId: string): Paper | undefined {
  return papers.find((p) => p.id === paperId && p.courseId === courseId);
}
